// AUTO-GENERATED by authoring/export_live.py -- DO NOT EDIT BY HAND.
//
// The single source of truth for the advertised question count. Derived from
// the authored bank at export time, so marketing copy cannot drift from what
// actually ships. src/db/__tests__ asserts these match AUTHORED_COUNT.
//
// Kept separate from authored-bank.ts on purpose: that module is several MB,
// and importing it into a page component would send the whole bank to the
// browser.

/** Exact number of authored questions currently shipped. */
export const QUESTION_COUNT = 3059;

/** Rounded-down marketing label, e.g. "2,900+". Always <= QUESTION_COUNT. */
export const QUESTION_COUNT_LABEL = "3,000+";

/** Number of questions carrying an original diagram. */
export const DIAGRAM_COUNT = 547;
