"use client";

import { useMemo, useState } from "react";

type Guide = { title: string; summary: string; sections: [string, string][]; tips: string[] };

const guides: Record<string, Guide> = {
  "heart failure": { title: "Heart failure", summary: "A syndrome in which the heart cannot pump or fill well enough to meet the body's needs. Left-sided failure mainly causes pulmonary congestion; right-sided failure causes systemic venous congestion.", sections: [["Key features", "Dyspnoea, orthopnoea, paroxysmal nocturnal dyspnoea, crackles, fatigue, oedema, raised jugular venous pressure and weight gain."], ["Assessment", "Monitor respiratory status, oxygen saturation, lung sounds, daily weight, intake and output, blood pressure, potassium and renal function."], ["Management principles", "Prescribed diuretics reduce fluid and preload. Sodium awareness, medication adherence, gradual activity and escalation of worsening breathlessness are important."], ["Red flags", "Severe breathlessness at rest, pink frothy sputum, confusion, chest pain or rapidly worsening oedema require urgent escalation."]], tips: ["Daily weight is often an early sign of fluid change.", "Left-sided failure is associated with pulmonary symptoms; right-sided failure with peripheral congestion."] },
  "sickle cell": { title: "Sickle-cell disease", summary: "An inherited haemoglobin disorder in which red cells can sickle, obstruct small vessels and cause haemolysis, anaemia and painful vaso-occlusive crises.", sections: [["Triggers", "Dehydration, infection, hypoxia, cold exposure, acidosis and physical stress can precipitate a crisis."], ["Assessment", "Assess pain, hydration, oxygenation, temperature, urine output, neurological status and signs of acute chest syndrome."], ["Management principles", "Provide prescribed analgesia, hydration and oxygen when indicated, treat infection promptly and encourage prevention planning."], ["Red flags", "Chest pain, cough, hypoxia, fever, sudden weakness, severe anaemia or reduced consciousness require urgent review."]], tips: ["Prevent dehydration and infection.", "New chest symptoms in a patient with sickle-cell disease are an emergency concern."] },
  "stroke": { title: "Stroke", summary: "A sudden neurological deficit caused by interrupted cerebral blood flow or bleeding. Most strokes are ischaemic, but haemorrhage must be excluded before thrombolysis.", sections: [["Warning signs", "Sudden facial droop, arm or leg weakness, speech difficulty, vision change, severe imbalance or sudden severe headache."], ["Priority assessment", "Use ABCs, establish the time last known well, check glucose, assess neurological status and activate the stroke pathway."], ["Management principles", "Urgent imaging distinguishes ischaemia from haemorrhage. Maintain airway safety, prevent aspiration and follow specialist treatment protocols."], ["Red flags", "Reduced consciousness, fixed dilated pupil, worsening weakness, seizure or severe headache require immediate escalation."]], tips: ["Time is brain: record the exact onset or last-known-well time.", "Never assume a stroke is haemorrhagic or ischaemic without appropriate assessment."] },
  "hypertension": { title: "Hypertension", summary: "Persistently elevated arterial blood pressure that increases the risk of stroke, coronary disease, heart failure and kidney disease.", sections: [["Risk factors", "Age, family history, excess sodium, obesity, inactivity, smoking, alcohol and some medicines or secondary diseases."], ["Assessment", "Use correct cuff size, repeat abnormal readings, assess symptoms and screen for target-organ effects."], ["Management principles", "Lifestyle measures include lower sodium intake, more fruits and vegetables, physical activity, healthy weight and prescribed medication adherence."], ["Urgent concerns", "Very high pressure with chest pain, breathlessness, neurological deficit, confusion or visual symptoms needs urgent assessment."]], tips: ["Hypertension may be silent; regular measurement matters.", "The DASH pattern is rich in fruits and vegetables and lower in sodium."] },
  "meningitis": { title: "Meningitis", summary: "Inflammation of the meninges around the brain and spinal cord. Bacterial meningitis is a medical emergency.", sections: [["Key features", "Fever, severe headache, neck stiffness, vomiting, photophobia, altered consciousness, irritability or a bulging fontanel in an infant."], ["Priority care", "Assess ABCs, isolate according to local protocol, obtain urgent cultures and administer prescribed treatment without avoidable delay."], ["Safety", "Monitor neurological status, seizures, hydration and signs of raised intracranial pressure."], ["Red flags", "Reduced consciousness, seizures, shock, non-blanching rash or rapidly worsening symptoms require immediate escalation."]], tips: ["A bulging fontanel may be an important infant sign.", "Use appropriate infection-control precautions and urgent referral pathways."] },
  "postpartum haemorrhage": { title: "Postpartum haemorrhage", summary: "Excessive bleeding after birth. Uterine atony is a common cause and requires immediate action while help is called.", sections: [["Assessment", "Check blood loss, uterine tone and height, vital signs, consciousness, perfusion and bladder status."], ["Immediate principles", "Call for help, massage a boggy uterus, establish access, monitor observations and prepare prescribed uterotonics and fluids."], ["Causes", "Think of the four Ts: tone, tissue, trauma and thrombin."], ["Red flags", "Heavy ongoing bleeding, shock, worsening tachycardia, hypotension or reduced consciousness require emergency management."]], tips: ["A soft, high uterus suggests atony.", "Stabilisation and referral happen together; do not delay urgent action while waiting for transfer."] },
};

export default function TopicExplainer() {
  const [topic, setTopic] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const matches = useMemo(() => Object.keys(guides).filter((key) => key.includes(topic.toLowerCase().trim()) || guides[key].title.toLowerCase().includes(topic.toLowerCase().trim())), [topic]);
  const guide = selected ? guides[selected] : null;

  return <div className="space-y-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 className="text-lg font-extrabold text-emerald-950">Learn a topic</h2><p className="mt-1 text-sm text-emerald-800">Enter a nursing topic to get a structured study explanation from NurseGrid&apos;s reviewed guides.</p><div className="mt-4 flex gap-2"><input value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="e.g. heart failure" className="min-w-0 flex-1 rounded-xl border border-emerald-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500" /><button type="button" onClick={() => setSelected(matches[0] ?? null)} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-800">Explain</button></div>{topic && !matches.length && <p className="mt-3 text-xs text-emerald-800">No reviewed guide matches yet. Try heart failure, sickle cell, stroke, hypertension, meningitis or postpartum haemorrhage.</p>}</div>{!guide && <div className="grid gap-3 sm:grid-cols-2">{Object.entries(guides).map(([key, item]) => <button key={key} type="button" onClick={() => { setTopic(item.title); setSelected(key); }} className="rounded-2xl border border-slate-200 bg-white p-4 text-left hover:border-emerald-300 hover:bg-emerald-50"><p className="font-bold text-slate-900">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.summary}</p></button>)}</div>}{guide && <article className="rounded-2xl border border-slate-200 bg-white p-5"><button type="button" onClick={() => setSelected(null)} className="text-xs font-bold text-emerald-700 hover:underline">← Choose another topic</button><h2 className="mt-3 text-2xl font-extrabold text-slate-950">{guide.title}</h2><p className="mt-2 leading-7 text-slate-600">{guide.summary}</p><div className="mt-5 grid gap-4 md:grid-cols-2">{guide.sections.map(([heading, text]) => <section key={heading} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold text-slate-900">{heading}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></section>)}</div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold text-amber-900">Exam tips</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-amber-900">{guide.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul></div><p className="mt-5 text-xs text-slate-400">Educational study aid only. Follow current clinical guidelines and local protocols for patient care.</p></article>}</div>;
}
