// Ghana-mapped care plan templates.
// Generated from /home/user/nursegrid/curriculum/careplans.py -- edit there, not here.
//
// British spelling, Celsius and mmol/L, Ghanaian clinical settings, and
// 'medical officer' rather than 'provider'. Each diagnosis is in PES format
// and every intervention carries a rationale, which is what the care plan
// completeness meter checks for.

import type { CarePlanFormValues } from "@/components/care-plans/CarePlanForm";

export const CARE_PLAN_TEMPLATES: { key: string; label: string; values: CarePlanFormValues }[] = [
  {
    key: "severe-malaria",
    label: "🦟 Severe Malaria — impaired consciousness",
    values: {
      title: "Ineffective Cerebral Tissue Perfusion — severe falciparum malaria",
      clientInfo: "24-year-old man admitted to a district hospital with a three-day history of fever. Drowsy but rousable. Rapid diagnostic test positive for Plasmodium falciparum.",
      assessment: "Subjective: family report two days of high fever, headache and vomiting, and that he became confused this morning.\nObjective: temperature 39.8 °C, respiratory rate 32/min, pulse 118/min, blood pressure 96/60 mmHg, capillary refill 4 seconds, Blantyre coma score reduced, RDT positive for P. falciparum, blood glucose 3.1 mmol/L, haemoglobin 7.8 g/dL.",
      nursingDiagnosis: "Ineffective Cerebral Tissue Perfusion related to parasitised erythrocyte sequestration in cerebral microvasculature as evidenced by reduced level of consciousness, tachypnoea and delayed capillary refill.",
      goals: "Client will regain full orientation to person, place and time within 48 hours of starting parenteral artesunate.\nClient will maintain blood glucose above 4.0 mmol/L throughout the acute phase.\nClient will show no seizure activity during admission.",
      interventions: [
        { action: "Administer intravenous artesunate 2.4 mg/kg at 0, 12 and 24 hours, then daily, exactly as prescribed.", rationale: "Artesunate clears parasitaemia faster than quinine and reduces mortality in severe malaria; the loading schedule front-loads the killing effect." },
        { action: "Check blood glucose four-hourly and before every artesunate dose.", rationale: "Hypoglycaemia is both a feature of severe malaria and a complication of treatment, and in an unconscious patient it produces no warning symptoms." },
        { action: "Position on the side with the head of the bed raised, and keep suction ready.", rationale: "A reduced level of consciousness removes the gag reflex, so the lateral position protects a patient who may vomit or convulse from aspirating." },
        { action: "Record level of consciousness, pupils and vital signs hourly until stable.", rationale: "Deterioration in cerebral malaria is measured by trend rather than by any single reading, so hourly observation detects a falling coma score early." },
        { action: "Monitor urine output hourly and report less than 0.5 mL/kg/hour.", rationale: "Acute kidney injury and blackwater fever are recognised complications, and falling output is the earliest sign." },
        { action: "Complete the parenteral course, then give a full course of artemether-lumefantrine once the client can swallow.", rationale: "Artesunate alone does not eliminate residual parasites; the oral follow-on course prevents recrudescence." },
        { action: "Explain to the family why a bed net and prompt testing matter for every household member.", rationale: "The index case indicates local transmission, so household prevention reduces the chance of a repeat admission." },
      ],
      evaluation: "After 48 hours the client is alert and orientated, temperature 37.2 °C, blood glucose stable above 4.5 mmol/L, no seizures recorded, urine output adequate. Goals met. Oral artemether-lumefantrine commenced and completed before discharge.",
      status: "completed",
    },
  },
  {
    key: "sickle-crisis",
    label: "🩸 Sickle Cell — vaso-occlusive crisis",
    values: {
      title: "Acute Pain — sickle cell vaso-occlusive crisis",
      clientInfo: "19-year-old woman with known haemoglobin SS disease, admitted with severe pain in both thighs and the lower back for two days.",
      assessment: "Subjective: rates the pain 9 out of 10, describes it as deep and throbbing, says her usual paracetamol at home has not helped.\nObjective: temperature 37.4 °C, pulse 108/min, respiratory rate 22/min, guarding both thighs, reluctant to move, haemoglobin 6.9 g/dL, mildly dehydrated with dry mucous membranes.",
      nursingDiagnosis: "Acute Pain related to tissue ischaemia from sickled erythrocytes occluding the microcirculation as evidenced by a self-reported pain score of 9 out of 10, guarding and tachycardia.",
      goals: "Client will report a pain score of 3 or less out of 10 within 24 hours.\nClient will maintain a fluid intake of at least 3 litres in 24 hours.\nClient will mobilise to the bathroom unaided before discharge.",
      interventions: [
        { action: "Give analgesia by the clock rather than on request, following the prescribed step of the analgesic ladder, and reassess 30 minutes after each dose.", rationale: "Vaso-occlusive pain is continuous, so scheduled dosing prevents the peaks that as-required dosing allows; reassessment shows whether the step is adequate." },
        { action: "Believe and record the client's own pain score at every observation round.", rationale: "Sickle cell pain is routinely under-treated because patients appear calm between waves; the client's report is the only valid measure." },
        { action: "Encourage oral fluids to 3 litres in 24 hours and run prescribed intravenous fluids if intake falls short.", rationale: "Haemodilution reduces blood viscosity and helps unblock the microcirculation, shortening the crisis." },
        { action: "Keep the client warm and avoid draughts or cold compresses over painful areas.", rationale: "Cold causes vasoconstriction, which worsens sickling; warmth encourages vasodilatation." },
        { action: "Measure temperature four-hourly and escalate any reading of 38 °C or above immediately.", rationale: "Functional asplenia leaves these clients vulnerable to overwhelming pneumococcal sepsis, so fever is an emergency and not simply part of the crisis." },
        { action: "Apply warm compresses and support painful limbs with pillows.", rationale: "Non-pharmacological measures increase local blood flow and reduce the analgesic requirement." },
        { action: "Review folic acid, penicillin prophylaxis and bed net use before discharge.", rationale: "Preventive measures reduce crisis frequency, and adherence commonly lapses between admissions." },
      ],
      evaluation: "After 24 hours pain is reported as 3 out of 10, oral intake 3.2 litres, no fever recorded, mobilising to the bathroom unaided. Goals met. Discharged with an analgesia plan and a follow-up appointment at the sickle cell clinic.",
      status: "completed",
    },
  },
  {
    key: "pph",
    label: "🚨 Postpartum Haemorrhage — uterine atony",
    values: {
      title: "Deficient Fluid Volume — primary postpartum haemorrhage",
      clientInfo: "28-year-old woman, para 4, one hour after a spontaneous vaginal birth at a district hospital. Estimated blood loss 900 mL and continuing.",
      assessment: "Subjective: reports feeling dizzy, cold and frightened.\nObjective: uterus soft and boggy above the umbilicus, heavy vaginal bleeding with clots, pulse 124/min, blood pressure 88/54 mmHg, respiratory rate 26/min, skin cool and clammy, placenta inspected and complete.",
      nursingDiagnosis: "Deficient Fluid Volume related to uterine atony following prolonged labour as evidenced by an estimated blood loss of 900 mL, a soft uterus, tachycardia and hypotension.",
      goals: "Client's uterus will be firm and centrally located within 15 minutes.\nBleeding will reduce to normal lochia within one hour.\nClient will maintain a systolic blood pressure above 100 mmHg and a pulse below 100/min within two hours.",
      interventions: [
        { action: "Call for help, then massage the uterine fundus until firm and express retained clots.", rationale: "Atony causes about seventy per cent of postpartum haemorrhage, and mechanical stimulation contracts the muscle that compresses the placental bed vessels." },
        { action: "Empty the bladder by catheterisation and keep the catheter in place to measure output.", rationale: "A full bladder displaces the uterus and prevents it contracting; the catheter also gives an hourly measure of renal perfusion." },
        { action: "Give oxytocin 10 IU intramuscularly as prescribed, and further uterotonics if the uterus stays soft.", rationale: "Oxytocin acts within minutes on oxytocin receptors in the myometrium and is first-line for atony." },
        { action: "Insert two wide-bore cannulae, take blood for grouping and cross-matching, and start the prescribed fluids.", rationale: "Two large cannulae allow rapid replacement, and cross-matched blood must be requested before it becomes critical." },
        { action: "Give tranexamic acid 1 g intravenously as prescribed, within three hours of birth.", rationale: "Tranexamic acid reduces death from bleeding, but only when given early; benefit falls sharply after three hours." },
        { action: "Record pulse, blood pressure and blood loss every 15 minutes and weigh swabs and pads.", rationale: "Visual estimation typically underestimates loss by about half, and a young woman compensates until she has lost a quarter of her volume." },
        { action: "If the uterus becomes firm but bleeding continues, inspect the cervix and vagina in good light.", rationale: "A firm uterus that keeps bleeding indicates trauma rather than atony, and a tear will not respond to any uterotonic." },
        { action: "Avoid ergometrine if the client has hypertension or pre-eclampsia.", rationale: "Ergometrine causes generalised vasoconstriction and can precipitate stroke or pulmonary oedema in a hypertensive woman." },
      ],
      evaluation: "Uterus firm within 10 minutes of massage and oxytocin, bleeding settled to normal lochia by 45 minutes. At two hours pulse 92/min, blood pressure 108/66 mmHg, urine output 60 mL/hour. Goals met. Haemoglobin checked and haematinics commenced.",
      status: "completed",
    },
  },
  {
    key: "pre-eclampsia",
    label: "🤰 Severe Pre-eclampsia — seizure risk",
    values: {
      title: "Risk for Injury — severe pre-eclampsia with impending eclampsia",
      clientInfo: "22-year-old primigravida at 34 weeks' gestation, admitted from antenatal clinic with a severe headache and visual disturbance.",
      assessment: "Subjective: reports a severe frontal headache, flashing lights and epigastric pain.\nObjective: blood pressure 168/112 mmHg on repeat, proteinuria 3+ on dipstick, brisk deep tendon reflexes with clonus, pitting oedema of the hands and face, foetal heart rate 148/min and regular, urine output 25 mL/hour.",
      nursingDiagnosis: "Risk for Injury (maternal seizure) related to cerebral irritability and vasospasm secondary to severe pre-eclampsia as evidenced by a blood pressure of 168/112 mmHg, headache, visual disturbance and clonus.",
      goals: "Client will remain free of seizure activity throughout admission.\nClient's blood pressure will fall below 150/100 mmHg within two hours of antihypertensive treatment.\nClient and foetus will remain stable until a delivery decision is made.",
      interventions: [
        { action: "Give magnesium sulphate by the prescribed Pritchard regimen: 4 g intravenously plus 10 g intramuscularly, then 5 g intramuscularly four-hourly.", rationale: "Magnesium sulphate is the only agent proven to prevent eclamptic seizures and halves the risk compared with diazepam." },
        { action: "Before every magnesium dose, confirm the patellar reflex is present, respiratory rate is at least 16/min and urine output is at least 100 mL over four hours.", rationale: "These three parameters detect magnesium toxicity in the order it appears, and reflexes disappear first, giving the earliest warning." },
        { action: "Keep calcium gluconate 1 g at the bedside with the giving set.", rationale: "Calcium gluconate antagonises magnesium at the neuromuscular junction and must be immediately available, not fetched from pharmacy." },
        { action: "Give the prescribed antihypertensive, such as oral nifedipine or intravenous hydralazine, and repeat observations every 15 minutes.", rationale: "Lowering severe hypertension prevents intracranial haemorrhage, which is the leading cause of maternal death in pre-eclampsia." },
        { action: "Nurse in a quiet, dimly lit room with cot sides padded and suction ready.", rationale: "Light and noise can precipitate a seizure in an irritable cortex, and preparation limits injury if one occurs." },
        { action: "Monitor the foetal heart rate as prescribed and report any deceleration.", rationale: "Placental perfusion is already compromised, and foetal compromise may force earlier delivery." },
        { action: "Give dexamethasone 6 mg intramuscularly 12-hourly for four doses as prescribed.", rationale: "At 34 weeks the foetal lungs are still immature, and corticosteroids reduce respiratory distress syndrome if delivery becomes necessary." },
        { action: "Maintain a strict fluid balance chart and report output below 30 mL/hour.", rationale: "These women are at risk of both renal impairment and pulmonary oedema, so fluid is restricted rather than pushed." },
      ],
      evaluation: "No seizure activity occurred. Blood pressure 142/92 mmHg at two hours. Reflexes present and respiratory rate above 16/min before every dose. Corticosteroid course completed. Goals met. Delivered by caesarean section at 35 weeks; mother and baby stable.",
      status: "completed",
    },
  },
  {
    key: "sam-child",
    label: "🍼 Severe Acute Malnutrition — child",
    values: {
      title: "Imbalanced Nutrition: Less Than Body Requirements — severe acute malnutrition",
      clientInfo: "18-month-old boy brought to a district hospital by his mother, who reports poor appetite and swelling of both feet for two weeks.",
      assessment: "Subjective: mother reports the child stopped breastfeeding at 12 months, eats mainly thin porridge, and has had diarrhoea on and off.\nObjective: weight 7.1 kg, mid-upper arm circumference 10.8 cm, bilateral pitting pedal oedema, thin sparse hair, temperature 35.9 °C, apathetic and reluctant to play, appetite test passed with RUTF.",
      nursingDiagnosis: "Imbalanced Nutrition: Less Than Body Requirements related to inadequate protein and energy intake as evidenced by a mid-upper arm circumference of 10.8 cm, bilateral pedal oedema and apathy.",
      goals: "Child will maintain a body temperature above 36.5 °C throughout the stabilisation phase.\nChild will tolerate the prescribed F-75 feeds without vomiting or abdominal distension for 48 hours.\nChild's oedema will resolve and appetite return before transition to F-100 or RUTF.",
      interventions: [
        { action: "Give F-75 formula in small frequent feeds, two-hourly day and night, exactly as prescribed during stabilisation.", rationale: "F-75 supplies maintenance energy without the protein and sodium load that would precipitate refeeding syndrome and heart failure in a depleted child." },
        { action: "Do not begin F-100 or high-energy feeding until oedema has resolved and appetite has returned.", rationale: "Feeding for catch-up growth before the metabolism has stabilised is a recognised cause of death in the first days of treatment." },
        { action: "Keep the child warm with clothing, a hat and close contact with the mother, and check temperature four-hourly.", rationale: "A malnourished child has little subcutaneous fat and a lowered metabolic rate, so hypothermia develops quickly and carries high mortality." },
        { action: "Check blood glucose on admission and treat any reading below 3 mmol/L.", rationale: "Depleted glycogen stores make hypoglycaemia common, and in an apathetic child it produces no obvious signs." },
        { action: "Give the prescribed broad-spectrum antibiotic even without obvious signs of infection.", rationale: "Malnutrition suppresses the inflammatory response, so serious infection is frequently present without fever or a raised white cell count." },
        { action: "Do not give iron during the stabilisation phase.", rationale: "Free iron promotes bacterial growth and oxidative injury while the child is still metabolically unstable; it is introduced only in the rehabilitation phase." },
        { action: "Give vitamin A and the prescribed micronutrients according to the national protocol.", rationale: "Vitamin A deficiency accompanies severe malnutrition and causes preventable blindness and increased mortality." },
        { action: "Teach the mother to prepare an enriched family diet and demonstrate the appetite test before discharge.", rationale: "Relapse is common when the child returns to the diet that caused the malnutrition, so the teaching is part of the treatment." },
      ],
      evaluation: "Temperature maintained above 36.5 °C. F-75 tolerated without vomiting. Oedema resolved by day 6 and appetite returned; transitioned to RUTF and gaining weight. Goals met. Enrolled in the outpatient therapeutic programme with two-weekly review.",
      status: "completed",
    },
  },
  {
    key: "tb-dots",
    label: "🫁 Pulmonary TB — starting DOTS",
    values: {
      title: "Ineffective Health Maintenance — newly diagnosed pulmonary tuberculosis",
      clientInfo: "34-year-old trader diagnosed with smear-positive pulmonary tuberculosis, starting treatment at a district hospital chest clinic.",
      assessment: "Subjective: reports a cough for two months, night sweats, and losing weight; worried about missing work and about what neighbours will say.\nObjective: weight 52 kg, temperature 37.8 °C, sputum smear positive for acid-fast bacilli, HIV test offered and negative, lives in a two-room house with five other people.",
      nursingDiagnosis: "Ineffective Health Maintenance related to a long treatment course, stigma and loss of earnings as evidenced by expressed concern about missing work and reluctance to disclose the diagnosis at home.",
      goals: "Client will describe the purpose, duration and common side effects of each of the four drugs before leaving the clinic.\nClient will attend for directly observed therapy on every scheduled day for the first two months.\nClient will name the household contacts to be screened before the next visit.",
      interventions: [
        { action: "Explain each drug simply: rifampicin, isoniazid, pyrazinamide and ethambutol for two months, then rifampicin and isoniazid for four.", rationale: "Understanding why four drugs are needed at once addresses the commonest reason for default, which is stopping when symptoms improve." },
        { action: "Warn that rifampicin turns urine, tears and sweat orange, and that this is harmless.", rationale: "An unexpected colour change frightens clients into stopping treatment, and a simple forewarning prevents it." },
        { action: "Give pyridoxine as prescribed alongside isoniazid.", rationale: "Isoniazid causes peripheral neuropathy by antagonising vitamin B6, and pyridoxine prevents it." },
        { action: "Teach the client to report any change in vision or difficulty telling red from green.", rationale: "Ethambutol can cause optic neuritis, which is reversible only if the drug is stopped promptly." },
        { action: "Teach cough hygiene, sputum disposal and opening windows for cross-ventilation at home.", rationale: "Transmission is airborne and highest in the first two weeks; ventilation and covering the mouth protect a crowded household." },
        { action: "Arrange screening for all household contacts, especially children under five.", rationale: "Young children progress rapidly from infection to disease, and contact screening finds cases that would otherwise present late." },
        { action: "Agree a directly observed therapy plan that fits the client's trading hours, and record attendance.", rationale: "Directly observed therapy is the national standard because it prevents the incomplete treatment that drives drug resistance." },
        { action: "Discuss who the client will tell at home and rehearse the words.", rationale: "Stigma drives concealment, and concealment prevents both adherence and contact screening." },
      ],
      evaluation: "Client explained all four drugs and their side effects in his own words. Attended every directly observed therapy appointment in month one. Four household contacts screened, including two children under five. Goals met. Sputum converted to negative at two months.",
      status: "active",
    },
  },
  {
    key: "neonatal-sepsis",
    label: "👶 Neonatal Sepsis — early onset",
    values: {
      title: "Risk for Impaired Gas Exchange — early-onset neonatal sepsis",
      clientInfo: "Male newborn, 18 hours old, born at 38 weeks after prolonged rupture of membranes lasting 26 hours. Admitted to the newborn unit.",
      assessment: "Subjective: mother reports the baby is not feeding as strongly as her previous child and feels cold to touch.\nObjective: axillary temperature 35.8 °C, respiratory rate 68/min with grunting and mild intercostal recession, heart rate 178/min, capillary refill 4 seconds, reluctant to suck, blood glucose 2.4 mmol/L.",
      nursingDiagnosis: "Risk for Impaired Gas Exchange related to systemic infection acquired through prolonged rupture of membranes as evidenced by tachypnoea of 68/min, grunting, recession and temperature instability.",
      goals: "Neonate will maintain an axillary temperature between 36.5 and 37.5 °C within two hours.\nNeonate will maintain a respiratory rate between 30 and 60/min without grunting within 24 hours.\nNeonate will maintain blood glucose above 2.6 mmol/L throughout admission.",
      interventions: [
        { action: "Give the prescribed intravenous antibiotics within one hour of the decision to treat, after taking blood cultures if this causes no delay.", rationale: "Neonatal sepsis progresses within hours, and every hour of delay increases mortality; cultures refine therapy later but must not postpone it." },
        { action: "Place the baby in skin-to-skin contact with the mother or in a pre-warmed cot, and check temperature hourly until stable.", rationale: "A newborn cannot shiver and has a large surface area relative to mass, so hypothermia both signals sepsis and worsens it by increasing oxygen consumption." },
        { action: "Check blood glucose four-hourly and treat any value below 2.6 mmol/L as prescribed.", rationale: "A septic newborn depletes glycogen quickly, and untreated hypoglycaemia causes permanent neurological injury." },
        { action: "Count the respiratory rate for a full minute and record grunting, recession and any apnoea.", rationale: "Grunting is the newborn's attempt to maintain end-expiratory pressure, and its appearance or loss tracks the illness more reliably than a single rate." },
        { action: "Support feeding with expressed breast milk by cup or tube if sucking is weak, rather than withholding feeds.", rationale: "Breast milk supplies immunoglobulins and reduces necrotising enterocolitis; withholding it removes protection at the moment it is most needed." },
        { action: "Perform hand hygiene before and after every contact and keep the cot area uncluttered.", rationale: "Hospital-acquired infection is the main avoidable danger in a newborn unit, and hands are the principal route." },
        { action: "Explain each intervention to the mother and encourage her presence and touch.", rationale: "A frightened mother separated from her baby produces less milk and engages less with care, both of which affect the outcome." },
      ],
      evaluation: "Temperature 36.8 °C within 90 minutes of skin-to-skin care. Grunting resolved by 20 hours, respiratory rate 48/min. Blood glucose maintained above 3.0 mmol/L. Goals met. Completed the antibiotic course and discharged breastfeeding well on day 8.",
      status: "completed",
    },
  },
  {
    key: "diabetic-foot",
    label: "🦶 Diabetic Foot Ulcer — impaired skin integrity",
    values: {
      title: "Impaired Skin Integrity — neuropathic diabetic foot ulcer",
      clientInfo: "58-year-old woman with type 2 diabetes for 11 years, admitted with an ulcer under the right great toe that she first noticed two weeks ago.",
      assessment: "Subjective: reports she felt no pain and only noticed the wound when she saw staining on her sandal; says she often walks barefoot at home.\nObjective: 3 cm ulcer over the right first metatarsal head with surrounding callus, malodorous discharge, absent monofilament sensation to the mid-foot, pedal pulses palpable, random blood glucose 14.2 mmol/L, temperature 37.6 °C.",
      nursingDiagnosis: "Impaired Skin Integrity related to peripheral neuropathy and sustained hyperglycaemia as evidenced by a 3 cm plantar ulcer with malodorous discharge and absent protective sensation.",
      goals: "Wound will show clean granulation tissue with no malodour within 14 days.\nClient will maintain fasting blood glucose between 4 and 7 mmol/L during admission.\nClient will demonstrate correct daily foot inspection before discharge.",
      interventions: [
        { action: "Perform wound care with the prescribed dressing regimen and document wound size, depth, base and odour at each change.", rationale: "Serial measurement is the only objective way to distinguish healing from deterioration, and odour signals infection before systemic signs appear." },
        { action: "Offload the ulcer using the prescribed device or crutches and reinforce that she must not weight-bear on that foot.", rationale: "A neuropathic plantar ulcer cannot heal while it is repeatedly traumatised, and without pain the client has no natural reminder to protect it." },
        { action: "Monitor blood glucose as prescribed and administer insulin or oral agents accordingly.", rationale: "Hyperglycaemia impairs neutrophil function and collagen synthesis, so the wound cannot heal until glycaemic control improves." },
        { action: "Observe for spreading cellulitis, increasing pain, fever or rising pulse, and escalate promptly.", rationale: "Diabetic foot infection can progress to osteomyelitis or sepsis quickly, and neuropathy masks the usual warning of increasing pain." },
        { action: "Inspect and document the condition of the opposite foot daily.", rationale: "The other foot carries the same neuropathy and the same risk, and is frequently overlooked while attention is on the ulcer." },
        { action: "Teach daily foot inspection using a mirror, washing and drying between the toes, and never walking barefoot.", rationale: "Most diabetic foot ulcers begin as an unnoticed minor injury, so daily inspection substitutes sight for the protective sensation that has been lost." },
        { action: "Advise that footwear be checked for stones or rough seams before every wearing.", rationale: "A small foreign body causes a full-thickness ulcer in an insensate foot without the client ever feeling it." },
        { action: "Refer to the dietitian and to podiatry or the diabetes clinic before discharge.", rationale: "Ulcer recurrence exceeds fifty per cent within three years without structured follow-up." },
      ],
      evaluation: "By day 14 the wound bed is granulating with no malodour and has reduced to 1.8 cm. Fasting glucose between 5.1 and 6.8 mmol/L. Client demonstrated foot inspection with a mirror correctly. Goals met. Discharged with protective footwear and a podiatry appointment.",
      status: "active",
    },
  },
  {
    key: "cholera",
    label: "💧 Cholera — severe dehydration",
    values: {
      title: "Deficient Fluid Volume — acute watery diarrhoea with severe dehydration",
      clientInfo: "30-year-old man brought to a health centre during a cholera outbreak, with profuse watery stools since the previous night.",
      assessment: "Subjective: reports more than ten episodes of watery stool and repeated vomiting, with intense thirst and cramping in the legs.\nObjective: lethargic, sunken eyes, skin pinch returns very slowly, unable to drink without help, pulse 132/min and weak, blood pressure 84/50 mmHg, no urine passed for eight hours, stool described as rice-water.",
      nursingDiagnosis: "Deficient Fluid Volume related to excessive gastrointestinal losses from acute watery diarrhoea as evidenced by a very slow skin pinch, sunken eyes, lethargy, a weak pulse of 132/min and eight hours of anuria.",
      goals: "Client will show signs of adequate hydration, with a normal skin pinch and alertness, within four hours.\nClient will pass urine within six hours of starting rehydration.\nClient will tolerate oral rehydration solution and maintain hydration without intravenous fluids by 24 hours.",
      interventions: [
        { action: "Start intravenous Ringer's lactate immediately by Plan C, giving 100 mL/kg in the prescribed divided volumes and timing.", rationale: "Severe dehydration is treated intravenously because a lethargic client cannot drink enough and death follows from hypovolaemic shock within hours." },
        { action: "Reassess hydration status every 15 to 30 minutes during the first hours.", rationale: "Fluid replacement in cholera must match ongoing losses, which can exceed a litre an hour, so a fixed rate set once is not sufficient." },
        { action: "Begin oral rehydration solution as soon as the client can drink, alongside the intravenous fluid.", rationale: "Oral solution replaces potassium and bicarbonate and allows the intravenous line to be stopped earlier." },
        { action: "Measure and record every stool and vomit, and continue replacing ongoing losses.", rationale: "Rehydration is not a single correction; losses continue and the deficit reopens if replacement stops when the client first looks better." },
        { action: "Give the prescribed antibiotic once vomiting has settled.", rationale: "Antibiotics shorten the duration of diarrhoea and reduce the volume of fluid needed, but they are an adjunct to rehydration and never a substitute." },
        { action: "Apply enteric precautions: gloves, hand hygiene with soap and running water, and safe disposal of stool and vomit.", rationale: "Cholera is transmitted by the faecal-oral route, and alcohol rub is less reliable than soap and water against contamination with organic matter." },
        { action: "Notify the case immediately under IDSR, on suspicion and without waiting for laboratory confirmation.", rationale: "Cholera is immediately notifiable because a single suspected case may signal an outbreak requiring a public health response." },
        { action: "Teach the household about safe water, handwashing and the early use of oral rehydration solution.", rationale: "Household transmission follows the index case, and early home treatment prevents the next severe presentation." },
      ],
      evaluation: "Skin pinch normal and client alert at three hours. Passed urine at four hours. Tolerating oral rehydration solution and changed to oral maintenance at 18 hours. Goals met. Case notified the same day and the family given oral rehydration sachets and water treatment advice.",
      status: "completed",
    },
  },
  {
    key: "hiv-adherence",
    label: "💊 HIV — starting antiretroviral therapy",
    values: {
      title: "Risk for Ineffective Therapeutic Regimen Management — newly diagnosed HIV",
      clientInfo: "27-year-old woman newly diagnosed with HIV at an antenatal clinic, at 20 weeks' gestation, starting lifelong antiretroviral therapy.",
      assessment: "Subjective: tearful, asks whether the baby will be infected and whether she must tell her husband; says she has not told anyone.\nObjective: weight 58 kg, WHO clinical stage 1, no opportunistic infection, commenced on the fixed-dose combination, foetal heart rate normal, haemoglobin 10.4 g/dL.",
      nursingDiagnosis: "Risk for Ineffective Therapeutic Regimen Management related to a new diagnosis, fear of disclosure and stigma as evidenced by expressed fear about telling her husband and having told no one.",
      goals: "Client will state the purpose of antiretroviral therapy and the importance of taking it at the same time daily before leaving the clinic.\nClient will describe the plan to protect the baby from infection, including infant prophylaxis and feeding.\nClient will identify one person she can safely confide in within two weeks.",
      interventions: [
        { action: "Explain that lifelong daily antiretroviral therapy suppresses the virus and that an undetectable viral load protects both her health and the baby.", rationale: "Understanding the purpose converts a burdensome daily tablet into a comprehensible act of protection, which is the strongest predictor of adherence." },
        { action: "Teach that the tablet is taken at the same time every day and what to do about a missed dose.", rationale: "Irregular timing allows drug levels to fall and resistance to develop, and most clients are never told what a missed dose actually requires." },
        { action: "Describe the infant prophylaxis plan: nevirapine from birth for six weeks, and early infant diagnosis testing.", rationale: "Mother-to-child transmission falls below five per cent when maternal therapy and infant prophylaxis are both delivered." },
        { action: "Counsel on exclusive breastfeeding for six months while on treatment, and explain why mixed feeding is riskier.", rationale: "Mixed feeding damages the infant gut mucosa and increases transmission, so exclusive breastfeeding with maternal therapy is safer than either alternative." },
        { action: "Explain cotrimoxazole prophylaxis for the infant from four to six weeks until HIV is excluded and breastfeeding has ended.", rationale: "Pneumocystis pneumonia peaks between three and six months and is a leading cause of infant death in exposed children." },
        { action: "Discuss disclosure without pressing for it, and offer couple counselling at the clinic.", rationale: "Disclosure improves adherence and allows partner testing, but forced disclosure can expose a woman to violence and must remain her decision." },
        { action: "Assure her of confidentiality and explain who in the team can see her record and why.", rationale: "Fear of an unintended breach in a small community is a common reason for defaulting, and a concrete explanation addresses it better than reassurance." },
        { action: "Arrange a follow-up appointment within two weeks and record a contact number with her consent.", rationale: "The first month carries the highest default risk, and early contact identifies problems while they are still solvable." },
      ],
      evaluation: "Client explained the purpose of therapy and correct timing in her own words. Described the infant prophylaxis and feeding plan accurately. Confided in her sister within ten days and attended the two-week review. Goals met. Viral load undetectable at 12 weeks.",
      status: "active",
    },
  },
  {
    key: "typhoid-perforation",
    label: "🔪 Typhoid Perforation — post-laparotomy",
    values: {
      title: "Risk for Infection — post-operative typhoid ileal perforation",
      clientInfo: "21-year-old student, first day after emergency laparotomy and repair of a typhoid ileal perforation at a district hospital.",
      assessment: "Subjective: reports pain at the wound rated 7 out of 10 on movement, and feels afraid to take a deep breath.\nObjective: temperature 38.2 °C, pulse 104/min, respiratory rate 22/min and shallow, midline wound with a clean dry dressing, nasogastric tube draining bile-stained fluid, urinary catheter in situ, bowel sounds absent.",
      nursingDiagnosis: "Risk for Infection related to a surgical wound, peritoneal contamination and multiple invasive devices as evidenced by a temperature of 38.2 °C, a midline laparotomy wound and indwelling nasogastric and urinary catheters.",
      goals: "Client's wound will remain free of purulent discharge, spreading redness or dehiscence throughout admission.\nClient's temperature will settle below 37.5 °C within 72 hours.\nClient will perform deep breathing and supported coughing hourly while awake from day one.",
      interventions: [
        { action: "Observe the wound at every dressing change for redness, swelling, discharge and separation of the edges, and document what is seen.", rationale: "Peritoneal contamination makes surgical site infection likely, and dehiscence is preceded by signs that are only detected if the wound is actually inspected." },
        { action: "Perform hand hygiene and use aseptic non-touch technique for every dressing and every device.", rationale: "Cross-infection through hands is the dominant route in a surgical ward, and this client already has three portals of entry." },
        { action: "Give the prescribed antibiotics at the correct times and record any missed dose.", rationale: "Blood and tissue levels fall between late doses, which is when resistant organisms are selected." },
        { action: "Teach and supervise hourly deep breathing and coughing while supporting the wound with a folded cloth.", rationale: "Shallow breathing after upper abdominal surgery causes basal atelectasis and pneumonia; splinting makes the manoeuvre tolerable enough to be done." },
        { action: "Give analgesia before mobilising or physiotherapy rather than after pain has built up.", rationale: "Uncontrolled pain is the main reason clients avoid breathing exercises and mobilisation, both of which prevent complications." },
        { action: "Review the need for the urinary catheter and the nasogastric tube daily and advocate removal as soon as clinically possible.", rationale: "The daily risk of catheter-associated infection is cumulative, so the strongest preventive measure is early removal." },
        { action: "Assist mobilisation out of bed on the first post-operative day unless contraindicated.", rationale: "Early mobilisation reduces venous thromboembolism, chest infection and prolonged ileus." },
        { action: "Explain to the client and family why food and drink are withheld until bowel sounds return.", rationale: "Families frequently bring food out of concern, and a clear explanation is more effective than a prohibition." },
      ],
      evaluation: "Wound remained clean and intact with no discharge. Temperature 37.1 °C by day three. Performed supported deep breathing hourly and mobilised on day one. Goals met. Nasogastric tube and catheter removed on day three; discharged on day nine with an outpatient wound review.",
      status: "completed",
    },
  },
  {
    key: "stroke-swallow",
    label: "🧠 Stroke — impaired swallowing",
    values: {
      title: "Risk for Aspiration — acute ischaemic stroke with dysphagia",
      clientInfo: "66-year-old man admitted with sudden right-sided weakness and slurred speech that began four hours ago.",
      assessment: "Subjective: family report he was well at breakfast, then dropped his cup and could not speak clearly; he is frustrated and trying to talk.\nObjective: right-sided hemiparesis with facial droop, dysarthria, coughs when given a sip of water, blood pressure 176/94 mmHg, temperature 37.1 °C, blood glucose 8.2 mmol/L, conscious and following commands.",
      nursingDiagnosis: "Risk for Aspiration related to impaired swallowing secondary to acute stroke as evidenced by coughing on a water swallow test, facial droop and dysarthria.",
      goals: "Client will remain free of aspiration, with a clear chest and no fever, throughout admission.\nClient will receive adequate nutrition and hydration by a safe route within 24 hours.\nClient will communicate his basic needs using an agreed method from day one.",
      interventions: [
        { action: "Keep the client nil by mouth, including oral medication, until a formal swallow assessment is completed.", rationale: "A failed water swallow test predicts aspiration, and aspiration pneumonia is a leading preventable cause of death after stroke." },
        { action: "Sit the client fully upright for all feeding once cleared, and keep him upright for 30 minutes afterwards.", rationale: "An upright posture uses gravity to protect the airway and reduces reflux into the pharynx after the meal." },
        { action: "Arrange the prescribed alternative route, such as a nasogastric tube, if swallowing remains unsafe at 24 hours.", rationale: "Delaying nutrition worsens outcome, and a temporary tube is preferable to either starvation or unsafe oral feeding." },
        { action: "Perform oral care at least twice daily even while the client is nil by mouth.", rationale: "Colonised oral secretions are aspirated in small amounts regardless of feeding route, and oral hygiene measurably reduces pneumonia." },
        { action: "Monitor temperature, respiratory rate and chest sounds each shift and report any new cough or fever.", rationale: "Aspiration pneumonia in stroke is often silent, with fever and tachypnoea appearing before any obvious choking episode." },
        { action: "Position the weak limbs in correct alignment and reposition two-hourly.", rationale: "A flaccid limb is vulnerable to subluxation and contracture, and immobility over a hemiparetic side causes pressure damage quickly." },
        { action: "Agree a simple communication method such as a picture board or yes-no signals, and allow time for responses.", rationale: "Dysarthria does not impair comprehension, and speaking for the client or rushing him increases frustration and low mood." },
        { action: "Refer to physiotherapy and speech and language therapy according to local pathways.", rationale: "Early rehabilitation improves functional recovery, and the swallow requires formal reassessment before diet is upgraded." },
      ],
      evaluation: "No aspiration occurred and the chest remained clear. Nasogastric feeding commenced at 20 hours, with swallow reassessed and a modified diet started on day four. Communicated needs using a picture board from day one. Goals met.",
      status: "active",
    },
  },
];
