// Core learning library topics (body systems, obstetric anatomy, ADPIE).
//
// Extracted from seed.ts so the admin curriculum-update route can import
// them without pulling in the full seed, which deletes and recreates
// users, questions and payment records.
//
// British spelling, SI units and NMC scope terminology throughout.

export type LearningTopicDef = {
  slug: string;
  title: string;
  category: string;
  icon: string;
  summary: string;
  overview: string;
  keyStructures: string[];
  normalFindings: string[];
  nursingNotes: string[];
  redFlags: string[];
  commonConditions: string[];
  imageUrl?: string | null;
  videoId?: string | null;
  videoTitle?: string | null;
  videoSource?: string | null;
  sortOrder?: number;
};

export const LEARNING_TOPIC_DEFS: LearningTopicDef[] = [
  {
    slug: "cardiovascular-system",
    title: "Cardiovascular System",
    category: "Body Systems",
    icon: "heart",
    summary: "The heart and blood vessels that circulate oxygen, nutrients, and waste throughout the body.",
    overview:
      "The cardiovascular system is a closed loop made up of the heart (a four-chambered pump) and blood vessels (arteries, veins, and capillaries). The right side of the heart pumps deoxygenated blood to the lungs (pulmonary circulation), and the left side pumps oxygenated blood to the rest of the body (systemic circulation). Cardiac output depends on heart rate and stroke volume, and stroke volume depends on preload, afterload, and contractility.",
    keyStructures: [
      "Four chambers: right atrium, right ventricle, left atrium, left ventricle.",
      "Four valves: tricuspid, pulmonic, mitral (bicuspid), and aortic — they keep blood flowing in one direction.",
      "Coronary arteries supply the heart muscle itself; the left main coronary artery is sometimes called the 'widow maker' when blocked.",
      "The conduction system: SA node (pacemaker) → AV node → bundle of His → Purkinje fibers.",
      "Arteries carry blood away from the heart (usually oxygenated, except pulmonary artery); veins carry blood back (usually deoxygenated, except pulmonary vein).",
    ],
    normalFindings: [
      "Heart rate: 60–100 beats/min in adults.",
      "Blood pressure: roughly 90/60–120/80 mmHg for most healthy adults.",
      "Capillary refill: less than 3 seconds.",
      "Regular S1 ('lub') and S2 ('dub') heart sounds, no murmurs, rubs, or gallops.",
      "Peripheral pulses (radial, pedal) palpable and equal bilaterally.",
    ],
    nursingNotes: [
      "Always compare blood pressure and heart rate to the client's own baseline, not just 'normal' ranges.",
      "Check apical pulse for a full minute before giving digoxin or other cardiac medications — hold and notify the medical officer if HR < 60.",
      "Assess for oedema, jugular vein distention, and daily weight gain as early signs of fluid overload in heart failure.",
      "Chest pain is never something to 'wait and see' about — get a 12-lead ECG and vital signs immediately.",
      "Teach clients to report new shortness of breath, chest pain, or swelling promptly, not just at the next appointment.",
      "Encourage smoking cessation, a heart-healthy diet, and regular activity as core prevention teaching for every cardiac client.",
    ],
    redFlags: [
      "Crushing, radiating chest pain with diaphoresis — treat as a possible MI until proven otherwise.",
      "New irregular heart rhythm with hypotension or dizziness.",
      "Sudden onset of severe shortness of breath with frothy pink sputum (possible acute pulmonary oedema).",
      "Absent or markedly diminished peripheral pulse in an extremity (possible arterial occlusion).",
    ],
    commonConditions: ["Hypertension", "Heart failure", "Myocardial infarction", "Atrial fibrillation", "Coronary artery disease", "Peripheral artery disease"],
    imageUrl: "/images/learning/cardiovascular-system.jpg",
    videoId: "QhiVnFvshZg",
    videoTitle: "Circulatory system and the heart",
    videoSource: "Khan Academy",
  },
  {
    slug: "respiratory-system",
    title: "Respiratory System",
    category: "Body Systems",
    icon: "lungs",
    summary: "The airway and lungs responsible for gas exchange — bringing in oxygen and removing carbon dioxide.",
    overview:
      "The respiratory system includes the upper airway (nose, pharynx, larynx) and lower airway (trachea, bronchi, bronchioles, alveoli). Gas exchange happens at the alveolar-capillary membrane, where oxygen diffuses into the blood and carbon dioxide diffuses out. Breathing is controlled primarily by the respiratory centre in the brainstem, which responds mainly to blood CO2 levels (and, in some chronic lung disease clients, to oxygen levels instead).",
    keyStructures: [
      "Upper airway: nose, pharynx, larynx (voice box) — warms, filters, and humidifies air.",
      "Lower airway: trachea branches into the right and left main bronchi, then smaller bronchioles.",
      "Alveoli: tiny air sacs surrounded by capillaries where gas exchange actually happens.",
      "Diaphragm: the main muscle of breathing; contracts to pull air in, relaxes to let air out.",
      "Pleura: a double-layered membrane around the lungs; the pleural space normally has negative pressure.",
    ],
    normalFindings: [
      "Respiratory rate: 12–20 breaths/min in adults.",
      "Oxygen saturation (SpO2): 95–100% on room air.",
      "Breath sounds clear bilaterally in all lung fields, no wheezes, crackles, or rhonchi.",
      "Symmetric chest rise and fall, unlabored breathing at rest.",
      "Pink, dry mucous membranes (in individuals without other pigmentation differences affecting assessment).",
    ],
    nursingNotes: [
      "Always assess breathing (rate, effort, and oxygen saturation) as part of your very first priority check — it's the 'B' in ABC.",
      "Position clients with breathing difficulty upright (high-Fowler's) to maximize lung expansion.",
      "Use pursed-lip breathing teaching for COPD clients to help them exhale more completely.",
      "In COPD clients, use caution with high-flow oxygen — some clients rely on a lower oxygen drive to breathe; monitor closely rather than withholding needed oxygen outright.",
      "Encourage coughing, deep breathing, and incentive spirometer use every 1–2 hours post-op to prevent atelectasis and pneumonia.",
      "A silent chest with no audible breath sounds in a person struggling to breathe is an emergency — it means very little air is moving at all.",
    ],
    redFlags: [
      "Oxygen saturation below 90%, or a significant drop from baseline.",
      "Stridor, use of accessory muscles, or nasal flaring — signs of severe respiratory distress.",
      "Sudden sharp chest pain with shortness of breath (possible pneumothorax or pulmonary embolism).",
      "Cyanosis of the lips or fingertips.",
    ],
    commonConditions: ["Asthma", "COPD", "Pneumonia", "Pulmonary embolism", "Pneumothorax", "Acute respiratory distress syndrome"],
    imageUrl: "/images/learning/respiratory-system.jpg",
    videoId: "qGiPZf7njqY",
    videoTitle: "Meet the lungs",
    videoSource: "Khan Academy",
  },
  {
    slug: "gastrointestinal-system",
    title: "Gastrointestinal System",
    category: "Body Systems",
    icon: "stomach",
    summary: "The digestive tract and accessory organs that break down food, absorb nutrients, and eliminate waste.",
    overview:
      "The GI tract is a long muscular tube from the mouth to the anus: oesophagus, stomach, small intestine (duodenum, jejunum, ileum), and large intestine (colon, rectum). Accessory organs — the liver, gallbladder, and pancreas — contribute bile and enzymes that aid digestion. Peristalsis (wave-like muscle contractions) moves food along, and most nutrient absorption happens in the small intestine.",
    keyStructures: [
      "Esophagus carries food to the stomach via peristalsis; the lower oesophageal sphincter normally prevents reflux.",
      "Stomach secretes acid and enzymes to begin protein digestion and churns food into chyme.",
      "Small intestine (duodenum, jejunum, ileum) is the primary site of nutrient absorption.",
      "Large intestine absorbs water and electrolytes and forms/stores stool before elimination.",
      "Liver produces bile (stored in the gallbladder) which emulsifies fats; pancreas secretes digestive enzymes and insulin.",
    ],
    normalFindings: [
      "Bowel sounds active in all four quadrants, roughly 5–30 sounds per minute.",
      "Soft, non-tender, non-distended abdomen.",
      "Regular bowel pattern (varies per person — anywhere from 3 times/day to 3 times/week can be normal).",
      "Brown, formed stool without blood, mucus, or excess fat.",
      "No nausea, vomiting, or reflux symptoms.",
    ],
    nursingNotes: [
      "Always auscultate bowel sounds before palpating the abdomen — palpation can artificially change bowel motility.",
      "Assess pain location and character carefully — right lower quadrant pain suggests appendicitis, right upper quadrant suggests gallbladder.",
      "Encourage early ambulation after abdominal surgery to help bowel function return and reduce ileus risk.",
      "Teach clients to increase fibre, fluids, and activity as the first-line approach to constipation before reaching for laxatives.",
      "NPO status must be respected strictly before procedures requiring sedation or surgery — aspiration risk is real.",
      "Monitor for return of bowel sounds and passage of flatus as key signs the GI tract is 'waking up' after surgery or illness.",
    ],
    redFlags: [
      "Absent bowel sounds with a distended, tympanic abdomen (possible bowel obstruction or ileus).",
      "Sudden relief of abdominal pain followed by a rigid, board-like abdomen (possible perforation).",
      "Coffee-ground emesis or black, tarry stools (possible GI bleeding).",
      "High fever with severe localized abdominal pain and rebound tenderness.",
    ],
    commonConditions: ["GERD", "Peptic ulcer disease", "Appendicitis", "Bowel obstruction", "Inflammatory bowel disease", "Cholecystitis"],
    imageUrl: "/images/learning/digestive-system.jpg",
    videoId: "wIN_OwWT2Kk",
    videoTitle: "Human digestive system",
    videoSource: "Khan Academy",
  },
  {
    slug: "renal-urinary-system",
    title: "Renal & Urinary System",
    category: "Body Systems",
    icon: "kidney",
    summary: "The kidneys, ureters, bladder, and urethra that filter blood, balance fluids, and eliminate waste as urine.",
    overview:
      "The kidneys filter blood through millions of nephrons, each with a glomerulus (filters blood) and a series of tubules (reabsorb needed substances, secrete waste). The kidneys regulate fluid balance, electrolytes, acid-base balance, and blood pressure (via the renin-angiotensin-aldosterone system), and produce erythropoietin to stimulate red blood cell production. Urine travels from the kidneys through the ureters to the bladder for storage, then out through the urethra.",
    keyStructures: [
      "Nephron: the functional unit of the kidney, made of the glomerulus, Bowman's capsule, and renal tubules.",
      "Glomerulus: a capillary tuft where blood is filtered under pressure.",
      "Renal tubules (proximal tubule, loop of Henle, distal tubule, collecting duct) reabsorb water, electrolytes, and glucose.",
      "Ureters: transport urine from each kidney to the bladder via peristalsis.",
      "Bladder: a muscular reservoir that stores urine until voiding.",
    ],
    normalFindings: [
      "Urine output: at least 30 mL/hr, or roughly 0.5 mL/kg/hr in adults.",
      "Urine clear to pale yellow, without blood, cloudiness, or strong odor.",
      "BUN and creatinine within normal reference ranges for the lab used.",
      "No costovertebral angle (flank) tenderness.",
      "Balanced intake and output over a 24-hour period.",
    ],
    nursingNotes: [
      "Monitor strict intake and output for any client with kidney concerns — trends matter more than a single number.",
      "A urine output under 30 mL/hr for two consecutive hours should be reported — it may signal impaired kidney perfusion.",
      "Hold or question nephrotoxic medications (like certain antibiotics or contrast dye) in clients with reduced kidney function.",
      "Encourage adequate hydration unless the client is on a fluid restriction — both extremes can harm the kidneys.",
      "Teach clients with chronic kidney disease to watch dietary potassium, phosphorus, and sodium intake.",
      "Assess for the age-related need to void frequently, and don't dismiss it — full-bladder discomfort or retention needs follow-up.",
    ],
    redFlags: [
      "Anuria (no urine output) or a sudden sharp drop in output.",
      "Potassium above 6.0 mEq/L in a client with kidney impairment — risk of dangerous cardiac arrhythmias.",
      "Severe flank pain radiating to the groin (possible kidney stone) with hematuria.",
      "New confusion or oedema in a client with known chronic kidney disease.",
    ],
    commonConditions: ["Urinary tract infection", "Acute kidney injury", "Chronic kidney disease", "Kidney stones (nephrolithiasis)", "Benign prostatic hyperplasia"],
    imageUrl: "/images/learning/renal-urinary-system.jpg",
    videoId: "cc8sUv2SuaY",
    videoTitle: "The kidney and nephron",
    videoSource: "Khan Academy",
  },
  {
    slug: "nervous-system",
    title: "Nervous System",
    category: "Body Systems",
    icon: "brain",
    summary: "The brain, spinal cord, and nerves that control movement, sensation, thought, and vital body functions.",
    overview:
      "The nervous system has two main divisions: the central nervous system (brain and spinal cord) and the peripheral nervous system (all the nerves branching out from it). The brain has specialized regions — the cerebrum for thought and voluntary movement, the cerebellum for balance and coordination, and the brainstem for vital functions like breathing and heart rate. The autonomic nervous system (sympathetic 'fight or flight' and parasympathetic 'rest and digest') controls involuntary functions.",
    keyStructures: [
      "Cerebrum: divided into lobes (frontal, parietal, temporal, occipital), responsible for thought, movement, and sensory processing.",
      "Cerebellum: coordinates balance, posture, and fine motor movement.",
      "Brainstem (midbrain, pons, medulla): controls breathing, heart rate, and consciousness — damage here is often life-threatening.",
      "Spinal cord: relays signals between the brain and body, and coordinates reflexes.",
      "Neurons communicate via electrical impulses and chemical neurotransmitters across synapses.",
    ],
    normalFindings: [
      "Alert and oriented to person, place, time, and situation (A&Ox4).",
      "Pupils equal, round, and reactive to light and accommodation (PERRLA).",
      "Glasgow Coma Scale score of 15 (fully alert).",
      "Symmetric strength, sensation, and reflexes bilaterally.",
      "Steady gait and normal coordination (e.g., finger-to-nose testing).",
    ],
    nursingNotes: [
      "Neurologic status can change quickly — reassess often, especially after head injury or stroke symptoms, and always compare to the client's baseline.",
      "Use the Glasgow Coma Scale consistently to communicate changes in level of consciousness clearly to the team.",
      "For suspected stroke, note the exact time symptoms started — this determines treatment eligibility (e.g., thrombolytics).",
      "Elevate the head of the bed 30 degrees and keep the neck neutral for clients at risk of increased intracranial pressure.",
      "Protect the airway and turn a seizing client to the side — never restrain their movements or put anything in their mouth.",
      "Reorient confused clients gently and frequently; keep familiar objects and consistent routines nearby.",
    ],
    redFlags: [
      "Sudden facial droop, slurred speech, or one-sided weakness (classic stroke signs — act fast).",
      "A widening pulse pressure with bradycardia and irregular respirations (Cushing's triad — sign of increased intracranial pressure).",
      "A seizure lasting longer than 5 minutes, or repeated seizures without regaining consciousness (status epilepticus).",
      "A new, severe 'worst headache of my life' (possible subarachnoid haemorrhage).",
    ],
    commonConditions: ["Stroke (CVA)", "Seizure disorder", "Traumatic brain injury", "Parkinson's disease", "Multiple sclerosis", "Increased intracranial pressure"],
    imageUrl: "/images/learning/nervous-system.jpg",
    videoId: "BY8DJeX_tGc",
    videoTitle: "Overview of neuron function",
    videoSource: "Khan Academy",
  },
  {
    slug: "musculoskeletal-system",
    title: "Musculoskeletal System",
    category: "Body Systems",
    icon: "bone",
    summary: "The bones, joints, and muscles that give the body structure, protect organs, and allow movement.",
    overview:
      "The musculoskeletal system includes 206 bones in the adult skeleton, the joints that connect them, and the skeletal muscles that move them. Bones also produce blood cells (in the marrow) and store minerals like calcium. Muscles work in pairs — one contracts while its opposite relaxes — to create smooth, controlled movement. Cartilage cushions joints, and ligaments and tendons stabilize and connect the system together.",
    keyStructures: [
      "Bones: provide structure, protect organs (like the skull protecting the brain), and store calcium.",
      "Joints: where two bones meet; types include hinge (knee), ball-and-socket (hip), and pivot (neck) joints.",
      "Skeletal muscle: voluntary, striated muscle attached to bone via tendons.",
      "Ligaments connect bone to bone; tendons connect muscle to bone.",
      "Bone marrow: the site of blood cell production, found in the centre of certain bones.",
    ],
    normalFindings: [
      "Full active range of motion in all joints without pain or crepitus.",
      "Muscle strength 5/5 (full strength against resistance) bilaterally.",
      "No swelling, deformity, or tenderness over bones or joints.",
      "Steady, coordinated gait.",
      "Intact sensation and pulses distal to any extremity injury.",
    ],
    nursingNotes: [
      "Always assess circulation, movement, and sensation (neurovascular checks) distal to a fracture or cast — do this regularly, not just once.",
      "Encourage weight-bearing exercise as tolerated to help maintain bone density, especially in older adults.",
      "After joint replacement surgery, follow the surgeon's positioning precautions closely (e.g., hip precautions to prevent dislocation).",
      "Teach proper body mechanics to clients and staff to prevent back injury during lifting or transfers.",
      "Pain that is sudden, severe, and unrelieved by medication after a cast is applied may signal compartment syndrome — report immediately.",
      "Encourage early mobilization after surgery when appropriate to reduce the risk of blood clots and muscle deconditioning.",
    ],
    redFlags: [
      "A pulseless, pale, or extremely painful extremity distal to a cast or injury (possible compartment syndrome).",
      "Visible bone deformity, shortening, or inability to bear any weight after trauma.",
      "Severe localized bone pain with fever (possible osteomyelitis).",
      "Sudden inability to move a limb after a fall in an older adult (possible hip fracture).",
    ],
    commonConditions: ["Osteoporosis", "Fractures", "Osteoarthritis", "Rheumatoid arthritis", "Compartment syndrome", "Hip fracture"],
    imageUrl: "/images/learning/musculoskeletal-system.jpg",
    videoId: "zGPvAK97jW0",
    videoTitle: "Skeletal Muscle & Muscle Contraction",
    videoSource: "Medical education video",
  },
  {
    slug: "endocrine-system",
    title: "Endocrine System",
    category: "Body Systems",
    icon: "hormone",
    summary: "The glands that release hormones directly into the bloodstream to regulate metabolism, growth, and stress response.",
    overview:
      "The endocrine system is a network of glands — including the hypothalamus, pituitary, thyroid, parathyroid, adrenal glands, pancreas, and gonads — that release hormones into the blood to regulate body-wide processes like metabolism, growth, blood sugar, stress response, and reproduction. The hypothalamus and pituitary gland act as master regulators, often controlling other glands through feedback loops.",
    keyStructures: [
      "Hypothalamus and pituitary gland: the 'master' control centre that regulates many other endocrine glands.",
      "Thyroid gland: regulates metabolism via T3 and T4 hormones; the parathyroid glands regulate calcium.",
      "Adrenal glands: produce cortisol (stress hormone) and aldosterone (fluid/electrolyte balance), plus adrenaline.",
      "Pancreas: produces insulin (lowers blood glucose) and glucagon (raises blood glucose).",
      "Hormones work through negative feedback loops — rising hormone levels typically signal the body to slow production.",
    ],
    normalFindings: [
      "Fasting blood glucose: roughly 70–100 mg/dL.",
      "TSH (thyroid-stimulating hormone) within the lab's normal reference range.",
      "Stable weight and energy level without unexplained changes.",
      "Normal growth and development patterns for age.",
      "Stable fluid balance and blood pressure.",
    ],
    nursingNotes: [
      "Never stop corticosteroids abruptly — the adrenal glands may not resume normal cortisol production right away, risking a crisis.",
      "Check blood glucose before giving insulin and treat hypoglycemia (shakiness, diaphoresis, confusion) immediately with fast-acting sugar.",
      "Monitor for signs of thyroid storm (high fever, tachycardia, agitation) in clients with hyperthyroidism, especially during stress or surgery.",
      "Teach clients with diabetes the 'sick day rules' — check glucose more often and never skip insulin entirely, even when not eating normally.",
      "Weigh clients with suspected fluid imbalance (e.g., SIADH, diabetes insipidus) at the same time daily using the same scale.",
      "Encourage consistent timing of hormone-replacement medications (like levothyroxine) for stable blood levels.",
    ],
    redFlags: [
      "Blood glucose below 70 mg/dL with confusion, shakiness, or diaphoresis (hypoglycemia).",
      "Fruity breath odor, rapid deep breathing, and very high blood glucose (possible diabetic ketoacidosis).",
      "Severe hypotension and weakness in a client who recently stopped steroids (possible adrenal/Addisonian crisis).",
      "High fever, severe tachycardia, and altered mental status in hyperthyroidism (possible thyroid storm).",
    ],
    commonConditions: ["Type 1 and type 2 diabetes", "Hypothyroidism", "Hyperthyroidism", "Addison's disease", "Cushing's syndrome"],
    imageUrl: null,
    videoId: "f_Z1zsR9lFM",
    videoTitle: "Intro to the endocrine system",
    videoSource: "Khan Academy",
  },
  {
    slug: "integumentary-system",
    title: "Integumentary System (Skin)",
    category: "Body Systems",
    icon: "skin",
    summary: "The skin, hair, and nails that form the body's first line of defence against infection and injury.",
    overview:
      "The integumentary system consists of the skin (epidermis, dermis, and subcutaneous tissue), hair, and nails. Skin serves as a protective barrier against pathogens and fluid loss, helps regulate body temperature, provides sensation, and synthesizes vitamin D when exposed to sunlight. Skin integrity is a core nursing focus because breakdown can quickly lead to infection.",
    keyStructures: [
      "Epidermis: the outermost layer, providing a waterproof barrier.",
      "Dermis: contains blood vessels, nerve endings, hair follicles, and sweat glands.",
      "Subcutaneous tissue: fatty layer that provides insulation and cushioning.",
      "Skin appendages: hair, nails, sweat glands, and sebaceous (oil) glands.",
      "Skin colour, temperature, and turgor provide important clues about circulation and hydration status.",
    ],
    normalFindings: [
      "Skin warm, dry, and intact without lesions, redness, or breakdown.",
      "Good skin turgor — skin returns to place quickly when gently pinched.",
      "Capillary refill under 3 seconds.",
      "Wounds (if present) show progressive healing without increasing redness, warmth, or drainage.",
      "No unusual bruising, rashes, or petechiae.",
    ],
    nursingNotes: [
      "Reposition immobile clients at least every 2 hours to prevent pressure injuries — this is one of the most preventable complications in nursing care.",
      "Use a validated tool (like the Braden Scale) to assess pressure injury risk on admission and regularly afterward.",
      "Keep skin clean and dry, especially in skin folds and incontinent clients, to prevent breakdown.",
      "Document wound characteristics (size, depth, drainage, surrounding skin) consistently so changes over time are easy to track.",
      "Teach clients to inspect their own skin daily, especially those with diabetes or reduced sensation in the feet.",
      "Use pillows and positioning devices to offload pressure from bony prominences (heels, sacrum, elbows).",
    ],
    redFlags: [
      "A stage III or IV pressure injury (exposing deep tissue, muscle, or bone).",
      "Signs of wound infection: increasing redness, warmth, swelling, purulent drainage, or fever.",
      "Sudden widespread rash with swelling of the face or difficulty breathing (possible severe allergic reaction).",
      "Non-blanchable redness over a bony prominence — an early warning sign of pressure injury.",
    ],
    commonConditions: ["Pressure injuries", "Cellulitis", "Skin tears", "Burns", "Allergic dermatitis"],
    imageUrl: null,
    videoId: "4zKjzl0futI",
    videoTitle: "Meet the skin! (Overview)",
    videoSource: "Khan Academy",
  },
  {
    slug: "hematologic-immune-system",
    title: "Hematologic & Immune System",
    category: "Body Systems",
    icon: "blood",
    summary: "The blood components and immune defenses that transport oxygen, fight infection, and support clotting.",
    overview:
      "Blood is made up of plasma, red blood cells (carry oxygen), white blood cells (fight infection), and platelets (support clotting). The immune system includes physical barriers (like skin), innate immunity (immediate, non-specific defence), and adaptive immunity (specific defence built through exposure or vaccination, involving lymphocytes like B cells and T cells). Bone marrow and lymphoid organs (spleen, lymph nodes, thymus) support blood cell production and immune function.",
    keyStructures: [
      "Red blood cells (erythrocytes): carry oxygen via haemoglobin; produced in bone marrow, stimulated by erythropoietin from the kidneys.",
      "White blood cells (leukocytes): include neutrophils, lymphocytes, and others that fight infection.",
      "Platelets (thrombocytes): small cell fragments essential for blood clotting.",
      "Lymphoid organs: spleen filters blood and old red blood cells; lymph nodes filter lymph fluid and house immune cells.",
      "The clotting cascade uses a series of clotting factors to form a stable clot after injury.",
    ],
    normalFindings: [
      "Haemoglobin: roughly 12–16 g/dL (varies by reference range and individual factors).",
      "White blood cell count: roughly 5,000–10,000/mm3.",
      "Platelet count: roughly 150,000–400,000/mm3.",
      "No unusual bruising, bleeding gums, or petechiae.",
      "No palpable, tender, or enlarged lymph nodes.",
    ],
    nursingNotes: [
      "Neutropenic clients (very low white blood cell counts) need protective precautions — limit crowds, fresh flowers, and raw produce.",
      "Monitor for bleeding precautions in clients with low platelet counts: use a soft toothbrush, avoid IM injections when possible, and handle gently.",
      "Watch for transfusion reactions closely in the first 15 minutes of any blood transfusion — stop immediately if signs occur.",
      "Encourage iron-rich foods for clients with iron-deficiency anaemia and teach that iron supplements can cause dark stools (expected, not alarming).",
      "A fever in a neutropenic client is always an emergency, even without other symptoms — it may be the only sign of serious infection.",
      "Handle sickle cell crisis with prompt pain control, oxygen, and hydration — pain is real and under-treatment is a common care gap.",
    ],
    redFlags: [
      "Fever in a client with a very low neutrophil count (neutropenic fever) — treat as a medical emergency.",
      "Signs of a transfusion reaction: chills, back pain, hives, or fever shortly after starting a transfusion.",
      "Petechiae, unusual bruising, or active bleeding with a very low platelet count.",
      "Severe pain crisis in a client with sickle cell disease.",
    ],
    commonConditions: ["Anaemia", "Leukemia", "Thrombocytopenia", "Sickle cell disease", "Neutropenia", "Deep vein thrombosis"],
    imageUrl: null,
    videoId: "rp7T4IItbtM",
    videoTitle: "Types of immune responses: innate and adaptive, humoral vs. cell-mediated",
    videoSource: "Khan Academy",
  },
  {
    slug: "obstetric-reproductive-anatomy",
    title: "Female Reproductive & Obstetric Anatomy",
    category: "Obstetric & Reproductive",
    icon: "baby",
    summary: "The female reproductive organs, pelvis, placenta, and foetal circulation relevant to pregnancy and childbirth.",
    overview:
      "The female reproductive system includes the ovaries (produce eggs and hormones), fallopian tubes (site of fertilization), uterus (where the foetus develops), cervix, and vagina. During pregnancy, the placenta forms as the vital connection between mother and foetus, delivering oxygen and nutrients and removing waste via the umbilical cord. The foetus has unique circulatory shortcuts — the ductus venosus, foramen ovale, and ductus arteriosus — that bypass the non-functioning foetal lungs and liver before birth, and normally close shortly after delivery.",
    keyStructures: [
      "Ovaries: produce eggs (ova) and the hormones estrogen and progesterone.",
      "Fallopian tubes: capture the released egg and are the usual site of fertilization.",
      "Uterus: a muscular organ (myometrium) lined by the endometrium, where the fertilized egg implants and the foetus develops.",
      "Cervix: the lower, narrow part of the uterus that dilates during labour to allow birth.",
      "Placenta and umbilical cord: exchange oxygen, nutrients, and waste between mother and foetus; the cord typically has two arteries and one vein.",
      "Foetal circulation shortcuts: the foramen ovale (between the atria), ductus arteriosus (connects pulmonary artery to aorta), and ductus venosus (bypasses the liver) — all normally close after birth as the newborn starts breathing air.",
      "Pelvic shape (gynecoid, android, anthropoid, platypelloid) can affect the ease of vaginal delivery; gynecoid is most favorable.",
    ],
    normalFindings: [
      "Fundal height in centimeters roughly matches weeks of gestation between 20–34 weeks.",
      "Foetal heart rate: 110–160 beats/min.",
      "Regular menstrual cycle roughly every 21–35 days (when not pregnant).",
      "Placenta implants in the upper uterus, away from the cervical os.",
      "Amniotic fluid volume within expected range for gestational age.",
    ],
    nursingNotes: [
      "Learn the 3 foetal circulation shortcuts (ductus venosus, foramen ovale, ductus arteriosus) — exams love asking why they close after birth (rising oxygen levels and changing pressures).",
      "Fundal height, foetal heart rate, and foetal movement are quick, reliable ways to screen foetal well-being at each prenatal visit.",
      "Painless, bright red bleeding in the third trimester suggests placenta previa — avoid vaginal exams until previa is ruled out.",
      "Sudden, severe abdominal pain with a rigid uterus and dark red bleeding suggests placental abruption — this is an emergency.",
      "During labour, monitor foetal heart rate patterns alongside contractions to assess how well the foetus is tolerating labour.",
      "After birth, a firm, midline fundus at or near the umbilicus is expected; a boggy fundus needs immediate massage and reassessment.",
    ],
    redFlags: [
      "Painless bright red vaginal bleeding in the third trimester (possible placenta previa).",
      "Sudden severe abdominal pain with a rigid, board-like uterus and dark bleeding (possible placental abruption).",
      "Late decelerations or minimal variability on the foetal heart tracing (possible foetal distress).",
      "A boggy, poorly contracted uterus after birth with heavy bleeding (possible uterine atony/postpartum haemorrhage).",
    ],
    commonConditions: ["Placenta previa", "Placental abruption", "Preeclampsia", "Ectopic pregnancy", "Postpartum haemorrhage", "Gestational diabetes"],
    imageUrl: "/images/learning/obstetric-reproductive-anatomy.jpg",
    videoId: "LjwqNB-WDZE",
    videoTitle: "Female reproductive system",
    videoSource: "Khan Academy",
  },
  {
    slug: "nursing-process-adpie",
    title: "The Nursing Process & Care Plans (ADPIE)",
    category: "Nursing Process",
    icon: "compass",
    summary: "The five-step framework nurses use to organize client care: Assessment, Diagnosis, Planning, Implementation, Evaluation.",
    overview:
      "The nursing process is a systematic, five-step method (remembered as ADPIE) that nurses use to identify and address a client's health needs. It's a continuous, cyclical process — evaluation often leads back to reassessment. A nursing care plan is simply the nursing process written down: it documents what you assessed, what problem you identified, what outcome you're working toward, what you'll do about it, and how you'll know it worked.",
    keyStructures: [
      "A — Assessment: collect subjective (what the client says) and objective (what you observe/measure) data.",
      "D — Diagnosis: identify the client's actual or potential problem using a nursing diagnosis (not a medical diagnosis) — often written as 'Problem related to Etiology as evidenced by Signs/Symptoms.'",
      "P — Planning: set specific, measurable, realistic, time-bound (SMART) goals and expected outcomes.",
      "I — Implementation: carry out nursing interventions, each with a rationale grounded in evidence.",
      "E — Evaluation: determine whether the goal was met, partially met, or not met, and revise the plan as needed.",
    ],
    normalFindings: [],
    nursingNotes: [
      "A nursing diagnosis is different from a medical diagnosis — it describes a human response to a health condition, not the disease itself.",
      "Good goals are SMART: Specific, Measurable, Achievable, Realistic, and Time-bound (e.g., 'Client will ambulate 50 feet with assistance by end of shift').",
      "Every intervention should have a rationale — this is what shows you understand WHY you're doing something, not just following a checklist.",
      "Evaluation isn't the end of the process — if a goal wasn't met, you reassess and revise the plan, not just note the failure.",
      "Prioritize nursing diagnoses using ABCs (airway, breathing, circulation) and Maslow's hierarchy of needs when a client has multiple problems.",
      "Care plans are living documents — update them as the client's condition and needs change throughout their care.",
    ],
    redFlags: [],
    commonConditions: [],
    imageUrl: null,
    videoId: "am9zN5calho",
    videoTitle: "The Nursing Process (ADPIE) explained",
    videoSource: "Nursing education series",
  },
];
