import { db } from "@/db";
import { learningTopics } from "@/db/schema";
import { eq } from "drizzle-orm";

// ---------------------------------------------------------------------------
// "Quick Reference" learning topics — the high-yield review content that
// premium competitors bundle with their question banks (lab values, memory
// aids, prioritisation frameworks, drug math, lifespan vitals). All content
// is original, written in the NurseGrid house style for the Ghana NMC exam.
//
// Inserted idempotently by slug so this can run safely against production
// without touching existing topics, bookmarks, or users.
// ---------------------------------------------------------------------------

export const EXTRA_LEARNING_TOPICS = [
  {
    slug: "lab-values-quick-reference",
    title: "Lab Values Quick Reference",
    category: "Quick Reference",
    icon: "lab",
    summary: "The normal ranges every exam question assumes you know — electrolytes, blood counts, renal, clotting, and drug levels in one place.",
    overview:
      "Exam questions rarely announce that a value is abnormal — they hand you the number and expect you to recognize it. This page collects the ranges worth memorizing cold. Study tip: learn the NORMAL range first, then learn what the body looks like just outside it on each side. Most lab questions are really asking 'high, low, or normal — and what does the nurse do about it?'",
    keyStructures: [
      "Sodium (Na+): 135–145 mEq/L — the 'water follows sodium' electrolyte; think neuro changes when it drifts.",
      "Potassium (K+): 3.5–5.0 mEq/L — the cardiac electrolyte; both directions cause dangerous rhythms.",
      "Calcium: 9.0–10.5 mg/dL — think muscles and nerves: low = tetany (Trousseau's, Chvostek's), high = weakness and confusion.",
      "Magnesium: 1.3–2.1 mEq/L — low magnesium looks like low calcium (hyperreflexia); high looks like sedation (absent reflexes).",
      "Glucose (fasting): 70–110 mg/dL — pair with HbA1c under ~6.5% for longer-term control.",
      "Haemoglobin: men ~14–18 g/dL, women ~12–16 g/dL; Hematocrit roughly three times the haemoglobin.",
      "WBC: 5,000–10,000/mm³ — under ~2,000 means protect the patient from infection (neutropenic precautions).",
      "Platelets: 150,000–400,000/mm³ — under ~50,000 means bleeding precautions; under 20,000 is critical.",
      "BUN: 10–20 mg/dL and Creatinine: 0.6–1.2 mg/dL — creatinine is the truer kidney marker; BUN also rises with dehydration.",
      "PT: ~11–12.5 sec with INR 2–3 on warfarin; aPTT therapeutic on heparin = 1.5–2× control (roughly 46–70 sec).",
      "Digoxin: 0.5–2.0 ng/mL — toxicity flags: nausea, visual changes, bradycardia; check potassium too.",
      "Lithium: 0.6–1.2 mEq/L — toxicity: diarrhoea, vomiting, tremor, ataxia; sodium and fluid changes swing the level.",
      "Albumin: 3.5–5.0 g/dL — low albumin = oedema and poor healing; also changes how protein-bound drugs behave.",
    ],
    normalFindings: [
      "ABGs: pH 7.35–7.45, PaCO2 35–45, HCO3 22–26, PaO2 80–100.",
      "Oxygen saturation: 95–100% for most healthy adults.",
      "Urine specific gravity: about 1.005–1.030 — high = concentrated (dehydration), very low = dilute (think DI).",
      "Total cholesterol under 200 mg/dL is the usual screening target.",
    ],
    nursingNotes: [
      "Always interpret a value against the CLIENT'S baseline and clinical picture, not the range alone.",
      "Potassium questions dominate exams: never give IV potassium as a push, and check urine output before adding it to fluids.",
      "A critical value is a report-now event — chart it AND tell the medical officer; documentation alone is a classic wrong answer.",
      "On anticoagulants, match the lab to the drug: heparin ↔ aPTT (antidote protamine), warfarin ↔ PT/INR (antidote vitamin K).",
      "For narrow-range drugs (digoxin, lithium, theophylline, phenytoin) know the toxicity picture as well as the number.",
    ],
    redFlags: [
      "K+ above ~6.0 or below ~2.5 — cardiac arrest territory; ECG and medical officer now.",
      "Sodium falling fast below 120 — seizure risk.",
      "Glucose under ~50 with symptoms — treat before you investigate.",
      "Platelets under 20,000 — spontaneous bleeding risk, including intracranial.",
    ],
    commonConditions: ["Hyperkalemia", "Hyponatremia", "Anaemia", "Neutropenia", "DKA", "Renal failure", "Warfarin therapy", "Digoxin toxicity"],
    imageUrl: null,
    videoId: null,
    videoTitle: null,
    videoSource: null,
    sortOrder: 20,
  },
  {
    slug: "nursing-mnemonics",
    title: "Mnemonics & Memory Hooks",
    category: "Quick Reference",
    icon: "brain",
    summary: "Short memory hooks for the facts that slip away under exam pressure — assessment order, hypoglycemia, cane walking, gluten grains, and more.",
    overview:
      "A good mnemonic is a rescue rope for exam day: when the mind blanks, the hook pulls the fact back. These are the memory aids our own question rationales lean on, gathered in one place. Say them aloud, write them once, and they stick.",
    keyStructures: [
      "ADPIE — Assessment, Diagnosis, Planning, Implementation, Evaluation: the nursing process order; assessment almost always comes first in 'what should the nurse do first?' questions.",
      "ABC — Airway, Breathing, Circulation: the priority ladder that outranks nearly everything else.",
      "The 6 rights of medication: right patient, drug, dose, route, time — and documentation.",
      "The 5 P's of compartment syndrome: Pain (unrelieved), Pallor, Pulselessness, Paresthesia, Paralysis — pain out of proportion is the earliest.",
      "'Hot and dry — sugar high; cold and clammy — need some candy': hyperglycemia vs hypoglycemia at the bedside.",
      "'Good goes up, bad goes down' — leading leg on stairs with a cane or crutches.",
      "BROW — Barley, Rye, Oats, Wheat: the gluten grains a celiac client must avoid.",
      "FAST — Face drooping, Arm weakness, Speech difficulty, Time to act: stroke recognition.",
      "RICE — Rest, Ice, Compression, Elevation for acute soft-tissue injury.",
      "COAL — Cane Opposite Affected Leg; and remember the nurse stands on the client's weak side.",
      "'Stones, bones, groans, and moans' — the hypercalcemia / hyperparathyroidism picture.",
      "MAOI 'forbidden feast': aged, cured, fermented, and pickled foods carry tyramine — one celebration meal can be a hypertensive crisis.",
    ],
    normalFindings: [],
    nursingNotes: [
      "Mnemonics answer 'what is the list?' — the exam asks 'what comes FIRST on the list?' Practice ranking, not just reciting.",
      "Make your own hook for anything you miss twice; a self-made mnemonic outlasts a borrowed one.",
      "Pair each mnemonic with one practice question so the memory hook connects to a clinical picture.",
    ],
    redFlags: [],
    commonConditions: ["Prioritisation", "Medication safety", "Stroke", "Diabetes", "Celiac disease", "Compartment syndrome"],
    imageUrl: null,
    videoId: null,
    videoTitle: null,
    videoSource: null,
    sortOrder: 21,
  },
  {
    slug: "prioritization-frameworks",
    title: "Prioritisation Frameworks",
    category: "Quick Reference",
    icon: "target",
    summary: "The decision rules behind every 'who do you see first?' question — ABC, Maslow, acute vs chronic, stable vs unstable, and safe delegation.",
    overview:
      "Prioritisation questions are won with frameworks, not memorized answers. When four clients compete for your attention, run them through the same filters in the same order and the answer usually falls out. This page is the filter set.",
    keyStructures: [
      "Filter 1 — ABC: airway beats breathing beats circulation; an unprotected airway outranks almost any other finding.",
      "Filter 2 — Maslow: physiological needs before safety, safety before psychosocial. The crying client waits for the bleeding one.",
      "Filter 3 — Acute vs chronic: a NEW problem beats a long-standing one, even when the chronic one sounds worse.",
      "Filter 4 — Unstable vs stable: trending-worse beats steady. Look for the client whose numbers are MOVING.",
      "Filter 5 — Assess before implement: if you haven't assessed, the assessment option usually wins — unless the scenario is a recognized emergency where action IS the assessment (dystonia, seizure, haemorrhage).",
      "Least restrictive first: verbal de-escalation before medication, medication before restraint — always in that order.",
      "Delegation rule: registered nurses keep assessment, teaching, evaluation, and unstable clients; Enrolled nurses take stable clients with predictable outcomes; ward assistants take routine care tasks.",
    ],
    normalFindings: [],
    nursingNotes: [
      "'Expected for the condition' findings rarely win a see-first question — hunt the finding that does NOT belong.",
      "In report-style questions, translate each client into one line: What system? Getting worse? New or old? Then rank.",
      "For phone-triage questions, imagine each caller an hour from now — return the call for the client whose next hour could be catastrophic.",
      "Post-op questions: know each surgery's signature complication (thyroidectomy → airway; hip replacement → dislocation; abdominal → haemorrhage then ileus).",
    ],
    redFlags: [
      "Answer choices that medicate away a warning sign (analgesia for unassessed pain under a cast).",
      "Options that pass the buck — calling the physician before your own assessment, when assessment is possible and safe.",
      "Restraint or seclusion options when a lesser step hasn't been tried.",
    ],
    commonConditions: ["Triage", "Delegation", "Report handoff", "Phone triage", "Post-op priorities"],
    imageUrl: null,
    videoId: null,
    videoTitle: null,
    videoSource: null,
    sortOrder: 22,
  },
  {
    slug: "medication-safety-calculations",
    title: "Drug Calculations & Med Safety",
    category: "Quick Reference",
    icon: "calc",
    summary: "The dose formula, drip-rate math, unit conversions, and high-alert drug rules — the numbers side of safe medication practice.",
    overview:
      "Every dosage question is one of a handful of set-ups. Master the basic formula, the drip-rate formula, and a short conversion table, and the math stops being the hard part — leaving you free to focus on the safety judgment the question is really testing.",
    keyStructures: [
      "Basic dose formula: (Desired ÷ Have) × Quantity. Example: order 500 mg, tablets are 250 mg each → (500 ÷ 250) × 1 = 2 tablets.",
      "IV drip rate (gtt/min): (Volume in mL × drop factor) ÷ time in minutes. Example: 1,000 mL over 8 h with a 15 gtt/mL set → (1000 × 15) ÷ 480 ≈ 31 gtt/min.",
      "mL/hour on a pump: total volume ÷ total hours. 1,000 mL over 8 h = 125 mL/h.",
      "Weight-based dosing: convert kg first (divide lb by 2.2), then multiply by the mg/kg order — and check it against the safe range.",
      "Conversions to know: 1 g = 1,000 mg; 1 mg = 1,000 mcg; 1 kg = 2.2 lb; 1 tsp = 5 mL; 1 tbsp = 15 mL; 1 oz = 30 mL; 1 L = 1,000 mL.",
      "Rounding rule of thumb: tablets to the half only if scored; mL doses usually to one decimal; drops to the whole number.",
    ],
    normalFindings: [],
    nursingNotes: [
      "A complete order needs drug, dose, route, and frequency — anything missing goes back for clarification before transcribing.",
      "High-alert families deserve a second check: insulin, anticoagulants, opioids, potassium, and chemotherapy.",
      "Never give IV potassium by push; dilute and use a pump.",
      "Insulin mixing: air into cloudy, air into clear, draw CLEAR (regular) first, then cloudy (NPH) — and match each insulin to ITS ordered units.",
      "If your answer requires a strange number of tablets or a huge volume, recheck the set-up — exam math usually lands on tidy numbers.",
      "Sound-alike drugs are a deliberate trap: read the full generic name, not the first syllable.",
    ],
    redFlags: [
      "Any calculated dose outside the reference safe range — hold and verify before giving.",
      "A verbal order for a high-alert drug without a read-back.",
      "An infusion 'catch-up' after a delay — never double a rate to make up time without an order.",
    ],
    commonConditions: ["Dosage calculation", "IV therapy", "Insulin administration", "Paediatric dosing", "High-alert medications"],
    imageUrl: null,
    videoId: null,
    videoTitle: null,
    videoSource: null,
    sortOrder: 23,
  },
  {
    slug: "vital-signs-lifespan",
    title: "Vital Signs Across the Lifespan",
    category: "Quick Reference",
    icon: "pulse",
    summary: "Normal heart rate, respirations, and blood pressure from newborn to older adult — the age-adjusted numbers behind every 'is this normal?' question.",
    overview:
      "A heart rate of 140 is an emergency in an adult and an ordinary Tuesday for a newborn. Age changes what 'normal' means, and exam writers love to test whether you know whose normal is whose. Anchor these ranges and half the paediatric vital-sign questions answer themselves.",
    keyStructures: [
      "Newborn: heart rate ~120–160/min (sleeping can dip lower), respirations ~30–60/min with brief periodic pauses, BP around 65–95/30–60.",
      "Infant (1–12 months): HR ~100–160, RR ~25–40 (count a FULL minute before disturbing the baby).",
      "Toddler (1–3 y): HR ~90–140, RR ~20–30.",
      "Preschool (3–5 y): HR ~80–120, RR ~20–25.",
      "School age (6–12 y): HR ~70–110, RR ~18–22.",
      "Adolescent to adult: HR ~60–100, RR ~12–20, BP settling toward ~120/80 or below.",
      "Older adults: temperature often runs LOWER (reduced metabolic rate), so 'normal' 37°C may already be a fever for them; BP tends to run higher with vascular stiffening.",
    ],
    normalFindings: [
      "Newborn apnea pauses under 15 seconds are normal periodic breathing — longer than 15 seconds is reportable.",
      "Acrocyanosis (blue hands and feet) is normal in the first hours after birth; central or circumoral cyanosis is not.",
      "Sinus arrhythmia (rate varying with breathing) is a normal finding in children and young adults.",
    ],
    nursingNotes: [
      "In infants, take the least disturbing measurements first: respirations by observation, then apical pulse, invasive temperature last.",
      "Count infant respirations and apical pulses for a FULL minute — their rhythms are naturally irregular.",
      "A child compensates long and crashes fast: a NORMAL blood pressure does not rule out shock; watch the heart rate and perfusion instead.",
      "Compare every reading against the client's own baseline — trend beats snapshot at every age.",
    ],
    redFlags: [
      "Newborn resting respiratory rate above 60 — sepsis or hypoxia sign.",
      "Quietly alert newborn with a heart rate above 160–180 — investigate; crying explains tachycardia, calm does not.",
      "Rising systolic pressure with a widening pulse pressure and slowing pulse after a head injury — increased intracranial pressure.",
      "Bradycardia in an infant is an emergency — their cardiac output depends on rate.",
    ],
    commonConditions: ["Paediatric assessment", "Newborn assessment", "Shock recognition", "Geriatric assessment", "Head injury"],
    imageUrl: null,
    videoId: null,
    videoTitle: null,
    videoSource: null,
    sortOrder: 24,
  },
  {
    slug: "malaria-ghana",
    title: "Malaria",
    category: "Ghana Priority Conditions",
    icon: "bug",
    summary: "The commonest reason for outpatient attendance in Ghana, and a leading cause of death in children under five.",
    overview: "Malaria in Ghana is overwhelmingly Plasmodium falciparum, the species that causes severe disease. Transmission is by the female Anopheles mosquito, which bites between dusk and dawn. The parasite invades red cells, and in falciparum infection the parasitised cells adhere to the walls of small vessels. That sequestration is what produces cerebral malaria, respiratory distress and organ failure. Every fever is treated as malaria until a test says otherwise, but the reverse is equally important: a negative test means the fever needs another explanation, not a repeat course of antimalarials.",
    keyStructures: [
      "Plasmodium falciparum is the dominant species in Ghana and the one that causes severe and cerebral malaria.",
      "The Anopheles mosquito bites at night, which is why an insecticide-treated net protects while a daytime repellent largely does not.",
      "Sequestration of parasitised red cells in cerebral and pulmonary microvessels causes the organ damage of severe disease.",
      "Rapid diagnostic tests detect parasite antigen and stay positive for some weeks after treatment; microscopy gives the parasite density.",
    ],
    normalFindings: [
      "A negative rapid diagnostic test in a febrile patient means look for another cause, not repeat the antimalarial.",
      "Uncomplicated malaria: fever, headache, joint pains, and the patient can drink, is alert and has no danger signs.",
      "Parasite clearance after artesunate is expected within 48 to 72 hours, with fever settling first.",
    ],
    nursingNotes: [
      "Test before treating whenever a test is available; presumptive treatment drives resistance and misses other causes of fever.",
      "Uncomplicated malaria is treated with artemether-lumefantrine; severe malaria needs parenteral artesunate.",
      "Artesunate dosing is weight-based: 3 mg/kg for children under 20 kg and 2.4 mg/kg at 20 kg or above, given at 0, 12 and 24 hours, then daily.",
      "Always complete a full oral course after parenteral treatment, because artesunate alone leaves residual parasites and allows recrudescence.",
      "Check blood glucose regularly in severe malaria: hypoglycaemia is caused by the disease and by the treatment, and is silent in an unconscious patient.",
      "In pregnancy, give IPTp-SP from 16 weeks, monthly, to at least three doses under direct observation.",
    ],
    redFlags: [
      "Reduced level of consciousness, confusion or convulsion — this is cerebral malaria and a medical emergency.",
      "Inability to drink or breastfeed, or vomiting everything.",
      "Respiratory distress or deep laboured breathing, which usually indicates metabolic acidosis.",
      "Passing dark or cola-coloured urine, suggesting blackwater fever and haemolysis.",
      "Severe anaemia with pallor, particularly in a young child.",
      "Shock, bleeding, or a urine output below 0.5 mL/kg/hour.",
    ],
    commonConditions: [
      "Uncomplicated falciparum malaria",
      "Severe and cerebral malaria",
      "Malaria in pregnancy",
      "Severe malarial anaemia in children",
      "Blackwater fever",
    ],
    sortOrder: 100,
  },
  {
    slug: "sickle-cell-ghana",
    title: "Sickle Cell Disease",
    category: "Ghana Priority Conditions",
    icon: "droplet",
    summary: "About two per cent of Ghanaian newborns have sickle cell disease, and preventable infection remains the biggest killer.",
    overview: "Sickle cell disease is inherited when a child receives an abnormal haemoglobin gene from both parents. Haemoglobin S polymerises when deoxygenated, distorting the red cell into a rigid sickle shape that blocks small vessels and is destroyed early. The two consequences follow from that: vaso-occlusion, which causes pain and organ damage, and chronic haemolysis, which causes anaemia and gallstones. Repeated splenic infarction leaves the child functionally asplenic within the first few years of life, which is why infection, not pain, is the leading cause of death. Newborn screening has been available in Kumasi since 1993.",
    keyStructures: [
      "Haemoglobin SS is the commonest severe form; haemoglobin SC disease also occurs frequently in Ghana and is generally milder.",
      "Sickle-shaped cells are rigid and adhere to vascular endothelium, obstructing the microcirculation.",
      "Red cell survival falls from about 120 days to around 20, producing chronic haemolytic anaemia.",
      "Repeated splenic infarction leads to functional asplenia, usually by five years of age.",
    ],
    normalFindings: [
      "Steady-state haemoglobin in sickle cell disease is often 6 to 9 g/dL — lower than normal, and not by itself a reason to transfuse.",
      "Mild scleral icterus between crises reflects ongoing haemolysis and is expected.",
      "Children are typically well between crises and should attend school normally.",
    ],
    nursingNotes: [
      "Give penicillin V prophylaxis from three months to at least five years, and ensure pneumococcal and Hib immunisation.",
      "Folic acid is needed lifelong because chronic haemolysis consumes it.",
      "Treat pain by the clock rather than on request, and believe the patient's own score — sickle pain is routinely under-treated.",
      "Encourage generous hydration and keep the patient warm; cold causes vasoconstriction and worsens sickling.",
      "Malaria prevention matters more in these children, because malaria precipitates crisis and severe anaemia.",
      "Discuss genotype testing before marriage sensitively; this is a normal part of counselling in Ghana.",
    ],
    redFlags: [
      "Fever of 38 °C or above — functional asplenia means this is a medical emergency; culture and treat without waiting.",
      "A rapidly enlarging spleen with pallor and shock: splenic sequestration, which can kill within hours.",
      "Chest pain with fever, cough and hypoxia: acute chest syndrome, the leading cause of death in adults.",
      "Sudden weakness on one side, or difficulty speaking: stroke, which occurs even in young children.",
      "A painful sustained erection lasting more than two hours: priapism requiring urgent treatment.",
      "Sudden severe pallor with a falling haemoglobin: aplastic crisis, often after parvovirus infection.",
    ],
    commonConditions: [
      "Vaso-occlusive crisis",
      "Acute chest syndrome",
      "Splenic sequestration",
      "Aplastic crisis",
      "Stroke in sickle cell disease",
      "Priapism",
      "Leg ulcers",
    ],
    sortOrder: 101,
  },
  {
    slug: "imci-ghana",
    title: "IMCI: The Sick Child Under Five",
    category: "Ghana Priority Conditions",
    icon: "baby",
    summary: "The structured approach used at every Ghanaian health facility to assess, classify and treat children under five.",
    overview: "Integrated Management of Childhood Illness gives a health worker a fixed order of assessment so that a sick child is never sent home with a missed danger sign. You check general danger signs first, then ask about the four main symptoms: cough or difficult breathing, diarrhoea, fever, and ear problems. Each is classified by colour — pink means urgent referral, yellow means treatment at the facility, green means home care with advice. The strength of the method is that it uses signs any trained health worker can elicit without a laboratory, and it deliberately errs towards referral.",
    keyStructures: [
      "General danger signs come first: unable to drink or breastfeed, vomits everything, convulsions, lethargic or unconscious.",
      "The four main symptoms: cough or difficult breathing, diarrhoea, fever, and ear problems.",
      "Classification is colour-coded: pink for urgent referral, yellow for treatment here, green for home care.",
      "Every visit also checks nutritional status, anaemia and immunisation, whatever the presenting complaint.",
    ],
    normalFindings: [
      "Respiratory rate is counted for a full minute while the child is calm; a crying child gives a falsely high count.",
      "Fast breathing thresholds: 60 or more under 2 months, 50 or more from 2 to 11 months, 40 or more from 12 months to 5 years.",
      "A child who drinks eagerly, is alert and playful, and has a normal skin pinch is not dehydrated.",
    ],
    nursingNotes: [
      "Chest indrawing means the lower chest wall moves in when the child breathes in — not the soft tissue between the ribs.",
      "Two signs are needed to classify dehydration in a given category.",
      "Diarrhoea is managed by Plan A at home, Plan B with oral rehydration at the facility, and Plan C with intravenous fluid for severe dehydration.",
      "Zinc is given with oral rehydration solution for 10 to 14 days in every child with diarrhoea.",
      "Give vitamin A at 6 months, then 200,000 IU six-monthly, and record it on the child health record book.",
      "A minor illness is not a contraindication to immunisation; use every contact as an opportunity to catch up.",
    ],
    redFlags: [
      "Any general danger sign — this alone means urgent referral regardless of the rest of the assessment.",
      "Chest indrawing or stridor in a calm child.",
      "Severe dehydration: lethargic, sunken eyes, very slow skin pinch, unable to drink.",
      "A stiff neck or bulging fontanelle, suggesting meningitis.",
      "Severe acute malnutrition: mid-upper arm circumference below 11.5 cm, or any bilateral pedal oedema.",
      "Severe palmar pallor.",
    ],
    commonConditions: [
      "Pneumonia",
      "Diarrhoea with dehydration",
      "Malaria",
      "Measles",
      "Acute ear infection",
      "Severe acute malnutrition",
      "Anaemia",
    ],
    sortOrder: 102,
  },
  {
    slug: "partograph",
    title: "The Partograph",
    category: "Obstetric & Reproductive",
    icon: "activity",
    summary: "A single chart that turns the progress of labour into a decision, and the main tool against obstructed labour.",
    overview: "The partograph plots cervical dilatation against time and adds foetal and maternal observations to the same page. Its power is that it converts a judgement into a rule: the alert line represents progress of one centimetre per hour from four centimetres, and the action line sits four hours to its right. Crossing the alert line means watch closely and, in a health centre, arrange transfer. Reaching the action line means the time for waiting has ended and a decision must be made by someone able to make it. Prolonged and obstructed labour causes uterine rupture, fistula, stillbirth and maternal death, and the partograph exists to prevent all four.",
    keyStructures: [
      "Cervical dilatation is plotted against time, beginning at 4 cm in the active phase.",
      "The alert line represents 1 cm per hour; the action line is drawn four hours to its right.",
      "Foetal heart rate, membranes and moulding are recorded above; contractions, drugs and maternal observations below.",
      "Descent of the head is recorded in fifths palpable abdominally, not by vaginal examination alone.",
    ],
    normalFindings: [
      "Foetal heart rate 110 to 160 beats per minute, recorded every 30 minutes in the active phase.",
      "Three to five contractions in ten minutes, each lasting 40 seconds or more, in established labour.",
      "Cervical dilatation progressing at 1 cm per hour or faster, keeping the plot on or left of the alert line.",
      "Clear liquor, and maternal temperature, pulse and blood pressure within normal limits.",
    ],
    nursingNotes: [
      "Plot findings as you take them; a partograph completed retrospectively at the end of labour has no value at all.",
      "Crossing the alert line calls for closer observation and, at a health centre, arrangements for transfer.",
      "Reaching the action line requires a clinical decision on augmentation, instrumental birth or caesarean section.",
      "Record every vaginal examination, and avoid performing them more often than necessary because each one carries infection risk.",
      "Moulding of the foetal skull graded 2 or 3 with poor progress suggests cephalopelvic disproportion.",
      "Encourage a companion of the woman's choosing throughout — it shortens labour and reduces intervention.",
    ],
    redFlags: [
      "Plot crossing to the right of the action line.",
      "Foetal heart rate below 110 or above 160, or decelerations after contractions.",
      "Thick meconium-stained liquor.",
      "A visible ridge across the lower abdomen with a tonically contracted uterus: Bandl's ring and impending uterine rupture.",
      "Maternal fever, tachycardia or offensive liquor, suggesting chorioamnionitis.",
      "Grade 3 moulding with the head not descending.",
    ],
    commonConditions: [
      "Prolonged labour",
      "Obstructed labour",
      "Cephalopelvic disproportion",
      "Foetal distress",
      "Chorioamnionitis",
      "Uterine rupture",
    ],
    sortOrder: 103,
  },
  {
    slug: "tb-ghana",
    title: "Tuberculosis and DOTS",
    category: "Ghana Priority Conditions",
    icon: "lungs",
    summary: "A curable disease whose treatment fails mainly through interruption, which is why observation is built into the therapy.",
    overview: "Tuberculosis is caused by Mycobacterium tuberculosis and spreads through droplet nuclei that remain suspended in the air of a poorly ventilated room. Most infected people never develop disease; HIV co-infection is the strongest driver of progression, which is why every tuberculosis patient is offered an HIV test and every HIV patient is screened for tuberculosis. Treatment is long, and the central clinical problem is that patients feel better within weeks while remaining infectious and incompletely treated. Directly observed therapy exists precisely because incomplete treatment produces drug resistance.",
    keyStructures: [
      "Mycobacterium tuberculosis is an acid-fast bacillus that spreads by airborne droplet nuclei.",
      "The standard regimen is two months of rifampicin, isoniazid, pyrazinamide and ethambutol, then four months of rifampicin and isoniazid.",
      "Sputum smear microscopy and GeneXpert are the mainstays of diagnosis; GeneXpert also detects rifampicin resistance.",
      "Transmission risk is highest in crowded, poorly ventilated indoor spaces.",
    ],
    normalFindings: [
      "Sputum conversion to smear-negative is expected by the end of the two-month intensive phase.",
      "Weight gain and resolution of night sweats are early signs that treatment is working.",
      "Orange discolouration of urine, tears and sweat on rifampicin is expected and harmless.",
    ],
    nursingNotes: [
      "Give pyridoxine with isoniazid to prevent peripheral neuropathy.",
      "Warn about rifampicin turning body fluids orange before the patient discovers it and stops the drug.",
      "Teach the patient to report any change in vision or difficulty distinguishing red from green: ethambutol can cause optic neuritis.",
      "Rifampicin is a powerful enzyme inducer and reduces the effectiveness of hormonal contraception; advise an additional method.",
      "Screen all household contacts, especially children under five, who progress rapidly from infection to disease.",
      "Offer HIV testing to every patient with tuberculosis, and tuberculosis screening at every HIV visit.",
    ],
    redFlags: [
      "Coughing blood, or breathlessness suggesting a pneumothorax or large effusion.",
      "Jaundice, nausea or right upper quadrant pain: drug-induced hepatitis, most often from pyrazinamide or isoniazid.",
      "Any new visual disturbance while on ethambutol.",
      "Failure of sputum to convert at two months, which raises the possibility of drug resistance.",
      "Neck stiffness, headache or confusion, suggesting tuberculous meningitis.",
      "Treatment interruption of two weeks or more.",
    ],
    commonConditions: [
      "Pulmonary tuberculosis",
      "Tuberculous lymphadenitis",
      "Tuberculous meningitis",
      "Pleural tuberculosis",
      "Multidrug-resistant tuberculosis",
      "TB-HIV co-infection",
    ],
    sortOrder: 104,
  },
  {
    slug: "ghs-structure",
    title: "The Ghana Health Service and Referral",
    category: "Nursing Process",
    icon: "building",
    summary: "How care is organised from the CHPS compound to the teaching hospital, and where the delays that kill occur.",
    overview: "Ghana's health system is organised in tiers, and knowing the tier tells you what a facility can and cannot do. Community-based Health Planning and Services brings a trained officer to live within the community itself; a zone covers roughly four to five thousand people within about four kilometres. Above that sit the health centre, the district hospital, the regional hospital and the teaching hospital. Understanding this structure matters clinically, because most maternal and newborn deaths are explained by the three delays: delay in deciding to seek care, delay in reaching a facility, and delay in receiving adequate care once there.",
    keyStructures: [
      "CHPS zone: a community health officer resident in the community, covering about 4,500 to 5,000 people within roughly 4 km.",
      "Health centre: outpatient care, normal deliveries, and basic emergency obstetric care.",
      "District hospital: the first level with surgery, caesarean section and blood transfusion.",
      "Regional hospital, then teaching hospital, for specialist and tertiary care. There are 16 regions.",
      "DHIMS/DHIS2 is the national reporting platform through which facility data flows upward.",
    ],
    normalFindings: [
      "A patient should be managed at the lowest level that can safely provide the care needed.",
      "Referral is accompanied by a written note stating findings, treatment given and the reason for referral.",
      "Routine data are reported monthly, and zero reporting is mandatory: a nil return is still a return.",
    ],
    nursingNotes: [
      "Stabilise before transferring: intravenous access, an airway that is protected, and treatment for hypoglycaemia and shock.",
      "Send the referral note, and where possible telephone ahead so the receiving facility is expecting the patient.",
      "Escort a critically ill patient if staffing allows; deterioration during transport is common and often unwitnessed.",
      "Know which nearby facility offers caesarean section and blood transfusion, because that determines where an obstetric emergency goes.",
      "Counsel families about the National Health Insurance Scheme and how to renew it, since cost is a major cause of the first delay.",
      "Report notifiable diseases immediately on suspicion under IDSR, without waiting for laboratory confirmation.",
    ],
    redFlags: [
      "An obstetric emergency at a facility without caesarean or transfusion capability — transfer without waiting.",
      "A patient who cannot afford transport; find another route rather than sending them home to arrange it.",
      "Referral of an unstable patient without intravenous access or an escort.",
      "A suspected outbreak condition: cholera, meningitis, yellow fever, measles or viral haemorrhagic fever.",
    ],
    commonConditions: [
      "Obstetric emergency referral",
      "Paediatric emergency referral",
      "Suspected outbreak notification",
      "Trauma referral",
    ],
    sortOrder: 105,
  },
];

// Insert any missing extra topics (idempotent by slug). Never deletes or
// modifies existing rows — safe to run against production repeatedly.
export async function insertExtraLearningTopics(): Promise<{ inserted: number; skipped: number }> {
  let inserted = 0;
  let skipped = 0;
  for (const t of EXTRA_LEARNING_TOPICS) {
    const existing = await db
      .select({ id: learningTopics.id })
      .from(learningTopics)
      .where(eq(learningTopics.slug, t.slug))
      .limit(1);
    if (existing.length > 0) {
      skipped += 1;
      continue;
    }
    await db.insert(learningTopics).values({
      slug: t.slug,
      title: t.title,
      category: t.category,
      icon: t.icon,
      summary: t.summary,
      overview: t.overview,
      keyStructures: [...t.keyStructures],
      normalFindings: [...t.normalFindings],
      nursingNotes: [...t.nursingNotes],
      redFlags: [...t.redFlags],
      commonConditions: [...t.commonConditions],
      imageUrl: t.imageUrl,
      videoId: t.videoId,
      videoTitle: t.videoTitle,
      videoSource: t.videoSource,
      sortOrder: t.sortOrder,
    });
    inserted += 1;
  }
  return { inserted, skipped };
}
