import type { AuthoredQuestion } from "./authored-bank";

/** Reviewed staging batch from the questions pasted in chat. Not imported until validation and approval. */
export const REVIEWED_PASTED_BATCH_1: AuthoredQuestion[] = [
  {
    authoredId: "NG-REVIEW-CARDIO-0001",
    categorySlug: "med-surg",
    stem: "Which of the following is a non-modifiable risk factor for coronary artery disease?",
    choices: [{ id: "a", text: "Hypertension" }, { id: "b", text: "Smoking" }, { id: "c", text: "Family history" }, { id: "d", text: "Obesity" }],
    correctChoiceId: "c",
    rationale: "Family history is non-modifiable. Hypertension, smoking and obesity are modifiable risk factors.",
    strategy: "Classify each risk factor as changeable or unchangeable before selecting the answer.",
    difficulty: "easy",
    tags: ["cardiovascular", "coronary-artery-disease", "risk-factors"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0002",
    categorySlug: "med-surg",
    stem: "Which description best matches typical angina pectoris pain?",
    choices: [{ id: "a", text: "Sharp pain relieved by deep breathing" }, { id: "b", text: "A constrictive, squeezing or choking sensation" }, { id: "c", text: "Burning pain that worsens after food" }, { id: "d", text: "A dull ache lasting several hours" }],
    correctChoiceId: "b",
    rationale: "Myocardial ischaemia classically produces pressure, tightness, squeezing or heaviness rather than sharp pleuritic pain.",
    strategy: "For cardiac chest pain, look for pressure or squeezing and consider the duration and triggers.",
    difficulty: "easy",
    tags: ["cardiovascular", "angina", "assessment"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0003",
    categorySlug: "med-surg",
    stem: "Which test most directly identifies coronary artery stenosis?",
    choices: [{ id: "a", text: "Chest radiograph" }, { id: "b", text: "Electrocardiogram" }, { id: "c", text: "Coronary angiography" }, { id: "d", text: "Cardiac MRI" }],
    correctChoiceId: "c",
    rationale: "Coronary angiography directly visualizes the coronary arteries and identifies the location and severity of stenosis.",
    strategy: "Choose the investigation that directly visualizes the structure named in the question.",
    difficulty: "medium",
    tags: ["cardiovascular", "coronary-angiography", "diagnostics"],
    isFree: true,
    mediaUrl: "/diagrams/reviewed-batch-1/coronary-artery-stenosis.png",
    mediaCaption: "Original educational illustration of coronary artery narrowing.",
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0004",
    categorySlug: "med-surg",
    stem: "Which complication is a life-threatening concern in a patient with pericarditis?",
    choices: [{ id: "a", text: "Myocardial infarction" }, { id: "b", text: "Cardiac tamponade" }, { id: "c", text: "Pulmonary embolism" }, { id: "d", text: "Aortic dissection" }],
    correctChoiceId: "b",
    rationale: "Pericardial fluid can compress the heart, impair ventricular filling and cause cardiac tamponade.",
    strategy: "When inflammation surrounds the heart, monitor for impaired filling and obstructive shock.",
    difficulty: "medium",
    tags: ["cardiovascular", "pericarditis", "cardiac-tamponade"],
    isFree: true,
    mediaUrl: "/diagrams/reviewed-batch-1/pericardial-tamponade.png",
    mediaCaption: "Original educational illustration of fluid compressing the heart in tamponade.",
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0005",
    categorySlug: "med-surg",
    stem: "Which rhythm is irregularly irregular and has no consistently formed P waves?",
    choices: [{ id: "a", text: "Atrial flutter" }, { id: "b", text: "Ventricular tachycardia" }, { id: "c", text: "Atrial fibrillation" }, { id: "d", text: "Sinus arrhythmia" }],
    correctChoiceId: "c",
    rationale: "Atrial fibrillation produces chaotic atrial activity, absent consistent P waves and an irregularly irregular ventricular rhythm.",
    strategy: "Irregularly irregular rhythm plus absent organized P waves points to atrial fibrillation.",
    difficulty: "medium",
    tags: ["cardiovascular", "ecg", "atrial-fibrillation"],
    isFree: true,
    mediaUrl: "/diagrams/reviewed-batch-1/atrial-fibrillation.png",
    mediaCaption: "Original educational ECG comparison for atrial fibrillation.",
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0006",
    categorySlug: "med-surg",
    stem: "What is the first-line treatment for pulseless ventricular tachycardia?",
    choices: [{ id: "a", text: "Atropine" }, { id: "b", text: "Amiodarone" }, { id: "c", text: "Immediate defibrillation" }, { id: "d", text: "Pacemaker insertion" }],
    correctChoiceId: "c",
    rationale: "Pulseless ventricular tachycardia is a shockable cardiac arrest rhythm. Begin resuscitation and deliver unsynchronized defibrillation as soon as possible.",
    strategy: "For pulseless shockable rhythms, prioritize CPR and defibrillation over medications.",
    difficulty: "medium",
    tags: ["cardiovascular", "cardiac-arrest", "defibrillation"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0007",
    categorySlug: "med-surg",
    stem: "Which finding is most characteristic of left-sided heart failure?",
    choices: [{ id: "a", text: "Dependent peripheral oedema" }, { id: "b", text: "Hepatomegaly" }, { id: "c", text: "Paroxysmal nocturnal dyspnoea" }, { id: "d", text: "Ascites" }],
    correctChoiceId: "c",
    rationale: "Left-sided failure causes pulmonary congestion, producing dyspnoea, orthopnoea and paroxysmal nocturnal dyspnoea.",
    strategy: "Left-sided failure primarily affects the lungs; right-sided failure produces systemic venous congestion.",
    difficulty: "easy",
    tags: ["cardiovascular", "heart-failure", "respiratory"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0008",
    categorySlug: "med-surg",
    stem: "Which medication class reduces preload in heart failure by removing excess body water?",
    choices: [{ id: "a", text: "Beta blockers" }, { id: "b", text: "ACE inhibitors" }, { id: "c", text: "Diuretics" }, { id: "d", text: "Positive inotropes" }],
    correctChoiceId: "c",
    rationale: "Diuretics promote sodium and water excretion, reducing circulating volume and venous return to the heart.",
    strategy: "Preload is reduced by reducing circulating volume; diuretics are the direct choice.",
    difficulty: "easy",
    tags: ["cardiovascular", "heart-failure", "diuretics"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0009",
    categorySlug: "med-surg",
    stem: "Which dietary pattern is recommended in the DASH approach to hypertension?",
    choices: [{ id: "a", text: "High sodium and low fat" }, { id: "b", text: "Low sodium and high saturated fat" }, { id: "c", text: "Low sodium with plentiful fruits and vegetables" }, { id: "d", text: "High protein and high refined carbohydrate" }],
    correctChoiceId: "c",
    rationale: "DASH emphasizes fruits, vegetables, whole grains and low-fat foods while limiting sodium and saturated fat.",
    strategy: "DASH means a heart-healthy, lower-sodium pattern rich in plant foods.",
    difficulty: "easy",
    tags: ["cardiovascular", "hypertension", "nutrition"],
    isFree: true,
  },
  {
    authoredId: "NG-REVIEW-CARDIO-0010",
    categorySlug: "med-surg",
    stem: "Which factor commonly precipitates a sickle-cell crisis?",
    choices: [{ id: "a", text: "Adequate hydration" }, { id: "b", text: "A high-oxygen environment" }, { id: "c", text: "Dehydration" }, { id: "d", text: "Bed rest" }],
    correctChoiceId: "c",
    rationale: "Dehydration increases blood viscosity and promotes sickling and vaso-occlusion.",
    strategy: "For sickle-cell disease, identify triggers that reduce flow or oxygen delivery, including dehydration, infection and hypoxia.",
    difficulty: "easy",
    tags: ["haematology", "sickle-cell", "crisis-prevention"],
    isFree: true,
    mediaUrl: "/diagrams/reviewed-batch-1/sickle-cell.png",
    mediaCaption: "Original educational illustration of sickle cells obstructing a vessel.",
  },
];
