// ---------------------------------------------------------------------------
// Additional clinical scenario items — expansion pack 1.
// Each item follows the same shape as the base banks in seed.ts:
//   [ scenario, priority finding, priority nursing action,
//     correct client/family/staff teaching statement, therapeutic outcome ]
// Adding items here automatically grows the generated question bank.
// ---------------------------------------------------------------------------

export type ExtraItem = [string, string, string, string, string];

export const EXTRA_FUNDAMENTALS: ExtraItem[] = [
  ["a client with a new indwelling urinary catheter", "cloudy, foul-smelling urine and a new fever", "use sterile technique during insertion and keep the drainage bag below bladder level", "I will keep the drainage bag below my bladder when walking", "the client remains free of catheter-associated urinary tract infection"],
  ["a client on strict bed rest at risk for pressure injuries", "a non-blanchable reddened area over the sacrum", "reposition the client at least every 2 hours and offload bony prominences", "I will shift my weight frequently and keep my skin clean and dry", "the client's skin remains intact without pressure injury"],
  ["a client learning to use crutches after a leg injury", "tingling and numbness in the hands after crutch walking", "teach the client to bear weight on the hands, not the axillae", "I will support my weight with my hands instead of leaning on my underarms", "the client ambulates safely with crutches without nerve injury"],
  ["a client with a nasogastric tube for gastric decompression", "sudden nausea, abdominal distention, and absent tube drainage", "check tube patency and irrigate per protocol when drainage stops", "I will tell the nurse if I feel nauseated or my stomach feels full", "the client's abdomen remains soft with adequate tube drainage"],
  ["a client receiving a cleansing enema", "abdominal cramping and dizziness during instillation", "slow the instillation and lower the solution container when cramping occurs", "I will breathe slowly through my mouth to relax during the procedure", "the client expels the enema with effective bowel evacuation"],
  ["a client with sequential compression devices after surgery", "new unilateral calf swelling and tenderness", "remove the devices and notify the provider if signs of deep vein thrombosis appear", "I will wear the compression sleeves whenever I am in bed as instructed", "the client remains free of venous thromboembolism during recovery"],
  ["a client with a Jackson-Pratt drain after abdominal surgery", "a sudden increase in bright red drainage output", "empty the drain, recompress the bulb, and record drainage amount and character", "I will empty the drain and write down the amount as taught", "the client's drainage decreases progressively without signs of bleeding or infection"],
  ["a client using home oxygen via nasal cannula", "redness and skin breakdown behind the ears from the tubing", "pad pressure points and assess skin under the tubing regularly", "I will keep oxygen away from open flames and never smoke while using it", "the client maintains target oxygen saturation without skin breakdown"],
  ["a client requiring a 24-hour urine collection", "a voided specimen discarded midway through the collection", "restart the collection whenever any urine is discarded during the 24 hours", "I will save every drop of urine for the full 24 hours after discarding the first void", "a complete 24-hour specimen is collected for accurate testing"],
  ["a client with bilateral wrist restraints ordered for safety", "fingers that are pale, cool, and swollen below the restraint", "release restraints every 2 hours to assess circulation, skin, and range of motion", "family will ask staff before releasing or adjusting the restraints", "the client remains injury-free with intact circulation while restraints are in use"],
];

export const EXTRA_PHARMACOLOGY: ExtraItem[] = [
  ["a client prescribed digoxin", "anorexia, nausea, and yellow-green visual halos", "check the apical pulse for one full minute before each dose", "I will hold my dose and call my provider if my pulse is below 60", "the client's heart rate and rhythm remain controlled without toxicity"],
  ["a client prescribed warfarin", "an INR of 4.8 with new gum bleeding", "hold the dose and notify the provider of the critically elevated INR", "I will keep my vitamin K food intake consistent from day to day", "the client's INR remains within the prescribed therapeutic range"],
  ["a client prescribed levothyroxine", "palpitations, tremors, and heat intolerance", "assess for signs of excess thyroid hormone and review the dose with the provider", "I will take this medication on an empty stomach first thing in the morning", "the client's thyroid levels normalize with resolution of hypothyroid symptoms"],
  ["a client prescribed phenytoin", "ataxia, nystagmus, and slurred speech with a high serum level", "hold the dose and report signs of phenytoin toxicity to the provider", "I will use a soft toothbrush and see my dentist regularly for gum care", "the client remains seizure-free with a therapeutic drug level"],
  ["a client prescribed lithium", "coarse tremors, vomiting, and confusion after becoming dehydrated", "hold lithium and obtain a serum level when toxicity is suspected", "I will keep my salt and fluid intake consistent every day", "the client's mood stabilizes with lithium levels in the therapeutic range"],
  ["a client prescribed intravenous vancomycin", "flushing of the face and neck during a rapid infusion", "infuse vancomycin slowly over at least 60 minutes to prevent a flushing reaction", "I will report ringing in my ears or changes in hearing right away", "the client's infection resolves without kidney injury or hearing loss"],
  ["a client prescribed long-term prednisone", "increased thirst, weight gain, and elevated blood glucose", "monitor blood glucose and never stop the corticosteroid abruptly", "I will take this medication with food and never stop it suddenly", "the client's inflammation is controlled with minimal steroid side effects"],
  ["a client prescribed an aminoglycoside antibiotic", "a rising serum creatinine and decreased urine output", "monitor peak and trough levels and renal function during therapy", "I will report dizziness or ringing in my ears immediately", "the client's infection clears without nephrotoxicity or ototoxicity"],
  ["a client taking sertraline who also uses St. John's wort", "agitation, diaphoresis, tremor, and hyperreflexia", "recognize possible serotonin syndrome and notify the provider immediately", "I will not take herbal supplements without checking with my provider first", "the client's depression improves without adverse drug interactions"],
  ["a client prescribed sublingual nitroglycerin", "chest pain unrelieved after the prescribed doses", "activate emergency services for chest pain unrelieved by nitroglycerin", "I will sit down before taking the tablet and let it dissolve under my tongue", "the client's chest pain is relieved and blood pressure remains adequate"],
];

export const EXTRA_MEDSURG: ExtraItem[] = [
  ["a client with acute pancreatitis", "severe epigastric pain radiating to the back with vomiting", "keep the client NPO and manage pain and IV fluids as prescribed", "I will avoid alcohol completely to prevent another attack", "the client's pain resolves and pancreatic enzyme levels return toward normal"],
  ["a client with cirrhosis and ascites", "increasing abdominal girth with worsening shortness of breath", "measure abdominal girth daily and position the client semi-Fowler's to ease breathing", "I will restrict sodium and take my diuretics as prescribed", "the client's ascites decreases with stable weight and comfortable breathing"],
  ["a client experiencing an acute ischemic stroke", "sudden facial droop, arm weakness, and slurred speech", "complete a rapid neurologic assessment and establish the time of symptom onset", "family will call emergency services immediately at the first signs of stroke", "the client's neurologic function improves without complications"],
  ["a client recovering from transurethral resection of the prostate", "bright red urine with clots obstructing the catheter", "maintain continuous bladder irrigation to keep the catheter patent", "I will drink plenty of fluids and avoid straining or heavy lifting", "the client's urine clears to pink-tinged without clots or obstruction"],
  ["a client in sickle cell vaso-occlusive crisis", "severe joint pain with fever and signs of dehydration", "administer IV fluids and prescribed analgesics promptly", "I will stay well hydrated and avoid high altitudes and extreme cold", "the client's pain resolves and hydration status normalizes"],
  ["a client with chronic stable angina", "chest pressure now occurring with progressively less exertion", "teach the client to rest and use nitroglycerin at the first sign of chest pain", "I will stop and rest at the first sign of chest discomfort", "the client performs daily activities without anginal episodes"],
  ["a client with a new colostomy", "a stoma that appears dusky and dark purple", "report a dusky stoma to the provider immediately because it signals impaired perfusion", "I will empty the pouch when it is one-third to one-half full", "the stoma remains pink and moist with functioning elimination"],
  ["a client with peptic ulcer disease", "sudden severe abdominal pain with a rigid, board-like abdomen", "keep the client NPO and notify the provider immediately for possible perforation", "I will avoid NSAIDs, smoking, and excessive alcohol", "the client's ulcer heals without bleeding or perforation"],
  ["a client with heart failure on daily weights", "a weight gain of 3 pounds in 24 hours with ankle swelling", "report the rapid weight gain and assess for worsening fluid overload", "I will weigh myself every morning and report a gain of more than 2 pounds in a day", "the client's weight stabilizes with clear lungs and minimal edema"],
  ["a client with diabetic ketoacidosis", "deep rapid respirations with a fruity breath odor", "administer IV insulin and isotonic fluids as prescribed with close electrolyte monitoring", "I will check my ketones whenever my blood sugar is high or I am ill", "the client's blood glucose, pH, and electrolytes return to normal ranges"],
];

export const EXTRA_MATERNAL: ExtraItem[] = [
  ["a laboring client with late decelerations on the fetal monitor", "recurrent late decelerations with decreasing variability", "reposition the client to her side, apply oxygen, and increase IV fluids", "I will lie on my side to improve blood flow to my baby", "the fetal heart rate returns to a reassuring pattern"],
  ["a postpartum client in the first hours after a vaginal birth", "a boggy uterus with heavy lochia and clots", "massage the fundus and assess for bladder fullness immediately", "I will report bleeding that soaks a pad within an hour", "the client's fundus remains firm with lochia decreasing appropriately"],
  ["a client with severe preeclampsia receiving magnesium sulfate", "absent deep tendon reflexes and a respiratory rate of 10 per minute", "stop the magnesium infusion and prepare to administer calcium gluconate", "I will report headaches, vision changes, or upper belly pain right away", "the client remains seizure-free with stable blood pressure and reflexes"],
  ["a newborn in the first hour after birth", "a respiratory rate of 80 with grunting and nasal flaring", "assess airway and oxygenation and notify the provider of respiratory distress", "family will place the baby on the back for every sleep", "the newborn maintains normal breathing, color, and temperature"],
  ["a client with placenta previa in the third trimester", "painless bright red vaginal bleeding", "avoid vaginal examinations and monitor bleeding and fetal status closely", "I will come to the hospital immediately if any bleeding starts", "the pregnancy continues safely without further bleeding episodes"],
  ["a breastfeeding client two weeks postpartum", "a red, painful area on one breast with fever and chills", "assess for mastitis and teach frequent, effective emptying of the breasts", "I will continue breastfeeding or pumping even if my breast is sore", "the client breastfeeds comfortably without infection"],
  ["a client in preterm labor receiving betamethasone", "contractions intensifying despite tocolytic therapy", "administer the corticosteroid doses on schedule to speed fetal lung maturity", "I understand these injections help my baby's lungs develop", "preterm birth is delayed and the newborn breathes without severe distress"],
  ["a newborn receiving phototherapy for jaundice", "lethargy, poor feeding, and a high-pitched cry", "shield the eyes and monitor temperature and hydration during phototherapy", "I will feed my baby frequently to help clear the bilirubin", "the newborn's bilirubin level decreases into the safe range"],
  ["a labouring client with an umbilical cord prolapse", "a visible loop of cord in the vagina after the membranes rupture", "relieve pressure on the cord with a gloved hand and call for emergency help", "I will stay in the knee-chest position until help arrives", "the fetus maintains a reassuring heart rate until emergency birth"],
  ["a Rh-negative client after giving birth to a Rh-positive newborn", "no Rho(D) immune globulin given as the 72-hour window approaches", "administer Rho(D) immune globulin within 72 hours of birth", "I understand this injection protects my future pregnancies", "the client does not develop Rh antibodies"],
];

export const EXTRA_PEDIATRICS: ExtraItem[] = [
  ["an infant with severe dehydration from gastroenteritis", "a sunken fontanel, absent tears, and markedly decreased wet nappies", "begin fluid replacement as prescribed and monitor intake and output strictly", "family will offer small, frequent amounts of oral rehydration solution", "the infant's fontanel, urine output, and alertness return to normal"],
  ["a child with suspected epiglottitis", "drooling, tripod positioning, and a muffled voice", "keep the child calm and never inspect the throat with a tongue blade", "family will keep the child's vaccinations up to date, including Hib", "the child's airway remains patent with resolution of the infection"],
  ["a toddler who swallowed an unknown number of iron tablets", "vomiting blood and lethargy after the ingestion", "contact poison control and prepare for emergency treatment immediately", "family will store all medications locked and out of the child's reach", "the child recovers without organ damage from the ingestion"],
  ["an infant with pyloric stenosis", "projectile vomiting after feeds with a palpable olive-shaped mass", "monitor for dehydration and prepare the infant for surgical repair", "family will follow the feeding instructions carefully after surgery", "the infant tolerates feedings and gains weight after repair"],
  ["a child having a tonic-clonic seizure", "jerking movements with cyanosis lasting more than 5 minutes", "protect the child from injury, time the seizure, and give nothing by mouth", "family will turn the child on the side and never put anything in the mouth", "the child recovers fully after the seizure without injury"],
  ["an infant with bronchiolitis from respiratory syncytial virus", "nasal flaring, chest retractions, and poor feeding", "suction the nares before feeds and monitor oxygenation closely", "family will wash hands frequently and keep the baby away from smoke", "the infant breathes comfortably and feeds well"],
  ["a child with newly diagnosed asthma using a metered-dose inhaler", "improper inhaler technique without a spacer", "teach inhaler use with a spacer and verify with a return demonstration", "I will use my controller inhaler every day even when I feel fine", "the child's asthma symptoms and night-time cough decrease"],
  ["a child with acute glomerulonephritis after a streptococcal infection", "tea-coloured urine, periorbital edema, and elevated blood pressure", "monitor blood pressure, weight, and urine output daily", "family will complete the full course of prescribed antibiotics for strep throat", "the child's urine clears and blood pressure returns to normal"],
  ["an adolescent with scoliosis prescribed a brace", "skin irritation under the brace and refusal to wear it at school", "assess the skin under the brace and support adherence to the wearing schedule", "I will wear the brace the prescribed number of hours each day", "the spinal curve does not progress on follow-up imaging"],
  ["a child with suspected intussusception", "sudden crampy abdominal pain with red currant-jelly stools", "report currant-jelly stools immediately and prepare the child for an air enema", "family will return immediately if the symptoms come back after treatment", "the child's bowel obstruction resolves with normal stooling"],
];

export const EXTRA_MENTALHEALTH: ExtraItem[] = [
  ["a client expressing suicidal ideation with a plan", "a specific plan with access to lethal means", "initiate one-to-one observation and remove dangerous items immediately", "I will tell staff right away if I have thoughts of hurting myself", "the client remains safe and engages in safety planning"],
  ["a client experiencing alcohol withdrawal", "tremors, tachycardia, and visual hallucinations 48 hours after the last drink", "administer prescribed benzodiazepines and monitor with a withdrawal scale", "I will attend a support programme to help me stay sober", "the client completes withdrawal safely without seizures"],
  ["a client with schizophrenia experiencing command hallucinations", "voices telling the client to harm another person", "assess the content of the hallucinations and ensure the safety of everyone on the unit", "I will tell staff when the voices get louder or give commands", "the client's hallucinations diminish with medication adherence"],
  ["a client with panic disorder during an acute attack", "chest tightness, hyperventilation, and an overwhelming fear of dying", "stay with the client and coach slow, deep breathing in a calm, quiet space", "I will use slow breathing and grounding when I feel panic rising", "the client's panic attacks decrease in frequency and intensity"],
  ["a client with anorexia nervosa starting a refeeding plan", "electrolyte shifts and edema during early refeeding", "monitor electrolytes and cardiac status closely during refeeding", "I will follow my meal plan and remain for observation after meals", "the client gains weight steadily toward the agreed target range"],
  ["a client with bipolar disorder in acute mania", "no sleep for 3 days with rapid speech and reckless spending", "provide a low-stimulation environment and ensure rest, fluids, and easy-to-eat foods", "I will take my mood stabiliser daily even when I feel well", "the client sleeps through the night and mood stabilises"],
  ["a client with major depression two weeks into antidepressant therapy", "returning energy while the client still expresses hopelessness", "monitor closely for suicide risk as energy returns before mood improves", "I understand it may take several weeks before I feel the full effect", "the client reports improved mood, sleep, and daily functioning"],
  ["a client with post-traumatic stress disorder", "flashbacks triggered by loud noises with constant hypervigilance", "ground the client in the present during flashbacks using a calm, steady voice", "I will use my grounding techniques when a flashback begins", "the client's flashbacks and avoidance behaviours decrease"],
  ["a client who self-harms under emotional distress", "fresh superficial cuts after a conflict with a visitor", "assess the injuries and explore the feelings that preceded the self-harm without judgement", "I will use my coping skills and ask for help when I feel overwhelmed", "the client uses adaptive coping skills instead of self-harm"],
  ["an older client with delirium on the medical unit", "sudden confusion that worsens at night with fluctuating alertness", "identify and treat the underlying cause while reorienting the client frequently", "family will bring the client's glasses, hearing aids, and familiar objects", "the client returns to baseline mental status"],
];

export const EXTRA_FLUIDELECTROLYTE: ExtraItem[] = [
  ["a client with severe hyponatremia", "a very low serum sodium with new confusion", "correct sodium slowly as prescribed to prevent osmotic demyelination", "I will follow my fluid restriction as instructed", "the client's sodium rises gradually to a safe range with clear mentation"],
  ["a client with hypokalemia while taking diuretics", "muscle weakness with a flattened T wave on the ECG", "administer prescribed potassium replacement and monitor the cardiac rhythm", "I will eat potassium-rich foods like bananas and oranges", "the client's potassium returns to the normal range without arrhythmia"],
  ["a client with hypercalcemia", "lethargy, constipation, and bone pain", "increase hydration as prescribed and encourage safe mobility", "I will drink plenty of fluids unless my provider tells me otherwise", "the client's calcium decreases with improved alertness"],
  ["a client with respiratory acidosis from hypoventilation", "a low pH with a rising carbon dioxide level and drowsiness", "position the client upright and support ventilation as prescribed", "I will do my breathing exercises when I feel drowsy or short of breath", "the client's blood gases return toward normal with improved alertness"],
  ["a client with metabolic alkalosis from prolonged vomiting", "muscle cramps, dizziness, and slow shallow breathing", "replace fluids and electrolytes as prescribed and treat the cause of vomiting", "I will take my anti-sickness medicine before meals as directed", "the client's pH, potassium, and chloride normalise"],
  ["a client developing fluid overload during an IV infusion", "crackles in the lungs, a bounding pulse, and distended neck veins", "slow the infusion, raise the head of the bed, and notify the provider", "I will report sudden shortness of breath or swelling right away", "the client's lungs are clear with balanced intake and output"],
  ["a client with hypomagnesemia and chronic alcohol use", "tremors, hyperactive reflexes, and facial twitching", "administer prescribed magnesium and institute seizure precautions", "I will eat magnesium-rich foods such as green vegetables and nuts", "the client's magnesium normalises without seizures or arrhythmias"],
  ["an older client with poor oral intake and dehydration", "dark concentrated urine, dry mucous membranes, and dizziness on standing", "offer scheduled oral fluids and monitor orthostatic vital signs", "I will drink fluids regularly through the day even when I am not thirsty", "the client's urine lightens and dizziness resolves with rehydration"],
  ["a client with syndrome of inappropriate antidiuretic hormone", "concentrated urine with dilutional hyponatremia and weight gain", "enforce the prescribed fluid restriction and monitor sodium closely", "I understand why my fluids are limited even though I feel thirsty", "the client's sodium rises and weight returns to baseline"],
  ["a client with diabetes insipidus", "large volumes of dilute urine with extreme thirst", "replace fluids and administer desmopressin as prescribed", "I will take my medication and report increased thirst or urination", "the client's urine output and sodium stabilise within normal limits"],
];

export const EXTRA_SAFETY: ExtraItem[] = [
  ["a client on airborne precautions for tuberculosis", "a visitor entering the room without a respirator", "place the client in a negative-pressure room and ensure staff wear N95 respirators", "I will wear a surgical mask whenever I leave my room for tests", "no staff or visitors are exposed to tuberculosis"],
  ["a neutropenic client during chemotherapy", "a low-grade fever with a very low neutrophil count", "report any fever immediately because it may be the only sign of infection", "I will avoid fresh flowers, raw foods, and crowds while my counts are low", "the client remains free of infection during the neutropenic period"],
  ["a confused client at high risk for falls", "the client attempting to climb over the raised side rails at night", "move the client nearer the nursing station and apply a bed exit alarm", "family will call for staff help instead of assisting the client alone", "the client remains free of falls during the hospital stay"],
  ["a nurse preparing a high-alert medication", "two different concentrations of the same drug stored side by side", "have a second nurse independently verify high-alert medications before giving them", "I will ask the nurse to confirm my identity before every medication", "no medication errors occur with high-alert drugs"],
  ["a fire alarm sounding on the nursing unit", "smoke visible in the corridor near a client room", "follow RACE — rescue clients, activate the alarm, contain the fire, then extinguish or evacuate", "I will follow staff directions calmly during any fire emergency", "all clients are protected or evacuated without injury"],
  ["a client with a documented latex allergy scheduled for a procedure", "flushing and wheezing after contact with latex gloves", "flag the allergy, use latex-free equipment, and schedule the case first in the theatre", "I will wear a medical alert bracelet stating my latex allergy", "the client undergoes procedures without allergic reactions"],
  ["a client with a wound infection on contact precautions", "purulent wound drainage positive for a resistant organism", "wear a gown and gloves for all care and dedicate equipment to the client", "family will perform hand hygiene when entering and leaving the room", "the infection does not spread to other clients or staff"],
  ["a nurse handling used sharps after an injection", "a needlestick injury sustained while recapping a used needle", "never recap used needles — dispose of them immediately in the sharps container", "I understand used needles go straight into the sharps container", "staff remain free of needlestick injuries through safe sharps handling"],
  ["a client whose identification band is missing", "no identification band present during the medication round", "replace the band and verify identity with two identifiers before giving any medication", "I will remind staff to check my armband before my medications", "medications are administered to the correct client every time"],
  ["a hospitalized toddler in a cot", "cot rails left down while the toddler naps unattended", "keep cot rails fully raised whenever the child is unattended", "family will keep small objects and cords away from the cot", "the child remains safe from falls and choking during the stay"],
];

export const EXTRA_LEADERSHIP: ExtraItem[] = [
  ["a charge nurse assigning care on a busy medical unit", "a newly admitted, unstable client with chest pain", "assign the unstable client to an experienced registered nurse", "I will notify the charge nurse right away if my client's condition changes", "clients are assigned according to acuity and staff competency"],
  ["a nurse delegating tasks to assistive personnel", "an assistant asked to complete a task outside their permitted role", "delegate only routine tasks for stable clients — never assessment, teaching, or evaluation", "I will report what I observe to the nurse instead of interpreting it myself", "all delegated tasks are completed safely within each role's scope"],
  ["a nurse who witnesses a colleague diverting controlled drugs", "a coworker pocketing a controlled substance instead of wasting it", "report the observation to the nurse in charge immediately per policy", "I understand controlled substance wasting must always be witnessed", "controlled substances are handled and documented according to policy"],
  ["a client refusing a scheduled blood transfusion for religious reasons", "the client declining the transfusion after understanding the risks", "respect the informed refusal, notify the provider, and document the decision", "I understand the risks of refusing and my right to decline treatment", "the client's autonomy is respected and safe alternatives are explored"],
  ["a client signing consent for surgery", "the client unable to explain what the operation involves", "notify the surgeon that the client does not understand the procedure before signing", "I can ask my surgeon any questions before I sign the consent form", "consent is obtained only after the client demonstrates understanding"],
  ["a charge nurse managing conflict between two staff members", "an escalating argument between staff at the nurses' station", "address the conflict privately and keep the focus on client safety", "I will raise concerns respectfully and through the proper channels", "the team resolves conflicts professionally without affecting client care"],
  ["a nurse receiving a telephone prescription during an emergency", "a verbal order for a high-risk medication given over the phone", "write down the order and read it back to the prescriber for confirmation", "I will repeat back every telephone order before carrying it out", "telephone orders are verified, documented, and countersigned per policy"],
  ["a nurse pressured to discharge a client during a bed shortage", "a planned discharge for a client with still-unstable vital signs", "advocate for the client and escalate concerns before an unsafe discharge", "I will call the unit if my symptoms return after going home", "clients are discharged only when clinically stable with clear instructions"],
  ["a nurse floated to an unfamiliar specialty unit", "an assignment requiring skills the float nurse has not been trained in", "accept stable clients within personal competence and clearly communicate limitations", "I will speak up whenever an assignment exceeds my competence", "float assignments match nurse competency and clients remain safe"],
  ["a nurse who discovers a medication error", "a wrong dose administered although the client remains stable", "assess the client first, notify the provider, and complete an incident report", "I understand the incident report is used for learning, not punishment", "errors are reported transparently and systems are improved"],
];

export const EXTRA_HEALTHPROMO: ExtraItem[] = [
  ["an adult due for colorectal cancer screening", "a 45-year-old client who has never been screened", "teach that colorectal screening should begin at age 45 for average-risk adults", "I will book my screening test as my provider recommends", "the client completes the recommended colorectal cancer screening"],
  ["a client beginning a smoking cessation programme", "strong cravings and irritability in the first week of quitting", "offer nicotine replacement options and behavioural support strategies", "I will identify my triggers and use substitutes when cravings hit", "the client remains smoke-free at follow-up visits"],
  ["a woman practising breast self-awareness", "a new, fixed lump noticed in the upper outer quadrant", "teach the client to report any new breast changes promptly for evaluation", "I will report any new lumps or skin changes to my provider right away", "breast changes are detected early and evaluated promptly"],
  ["an older adult reviewing immunizations at a wellness visit", "no record of recommended vaccines for the client's age group", "review and update the recommended adult vaccines with the client", "I will receive the vaccines recommended for my age and health conditions", "the client is up to date on all recommended immunizations"],
  ["a client with prediabetes at a wellness check", "a fasting glucose above normal with a sedentary lifestyle", "counsel on weight management, activity, and diet to prevent progression to diabetes", "I will aim for at least 150 minutes of moderate exercise each week", "the client's glucose returns to the normal range with lifestyle changes"],
  ["a client planning pregnancy at a preconception visit", "no folic acid intake before conception", "teach daily folic acid to reduce the risk of neural tube defects", "I will take a folic acid supplement every day before and during early pregnancy", "the pregnancy progresses with normal fetal development"],
  ["an adult with elevated blood pressure at a community health fair", "a blood pressure well above normal on two separate readings", "refer the client for follow-up evaluation of sustained hypertension", "I will have my blood pressure rechecked and see my provider soon", "the client's blood pressure is evaluated and managed early"],
  ["an adolescent requesting confidential health counselling", "risky health behaviours disclosed during a private interview", "provide nonjudgemental counselling and explain the limits of confidentiality", "I can talk to my provider privately about my health questions", "the adolescent adopts safer health behaviours"],
  ["a client with obesity seeking weight management support", "a high BMI with knee pain that limits activity", "set realistic weight goals and recommend low-impact activities", "I will start with swimming or cycling to protect my joints", "the client loses weight gradually and remains active"],
  ["an older adult starting a new exercise programme", "chest tightness during the first brisk walk", "instruct the client to stop activity and seek evaluation for exertional chest pain", "I will stop and rest if I feel any chest discomfort during exercise", "the client exercises regularly without cardiac symptoms"],
];

export const EXTRA_RISKREDUCTION: ExtraItem[] = [
  ["a client after cardiac catheterization via the femoral artery", "a spreading hematoma at the insertion site", "apply direct pressure, keep the leg straight, and notify the provider", "I will keep my leg straight and report any warmth or swelling at the site", "the insertion site remains intact without bleeding"],
  ["a client being screened before an MRI scan", "the client reports an implanted pacemaker during screening", "screen for metal implants before any MRI and notify the provider of the device", "I will remove all jewellery and report any implanted devices before my scan", "the client completes imaging safely without device-related injury"],
  ["a client after an abdominal paracentesis", "dizziness and hypotension after rapid fluid removal", "monitor vital signs closely and administer albumin as prescribed", "I will call for help before getting up after the procedure", "the client remains hemodynamically stable after the procedure"],
  ["a client receiving a blood transfusion", "fever, chills, and low back pain fifteen minutes into the transfusion", "stop the transfusion immediately and keep the line open with normal saline", "I will report itching, chills, or back pain during my transfusion right away", "the client receives blood products without adverse reactions"],
  ["a client with a chest tube after thoracic surgery", "continuous vigorous bubbling in the water-seal chamber", "check the system for an air leak and notify the provider", "I will keep the collection unit below my chest at all times", "the lung re-expands with the chest tube functioning properly"],
  ["a client resting after a lumbar puncture", "a severe headache whenever the client sits upright", "keep the client flat and encourage fluids as prescribed", "I will lie flat for the prescribed time after the procedure", "the client's post-procedure headache resolves"],
  ["a client with a peripherally inserted central catheter", "new arm swelling and redness around the insertion site", "measure the arm circumference, pause infusions, and notify the provider", "I will keep the dressing clean, dry, and intact between visits", "the line remains patent without thrombosis or infection"],
  ["a client preparing for a colonoscopy", "brown stool still returning after the bowel preparation is finished", "notify the provider that the bowel preparation is incomplete", "I will take only clear liquids the day before my procedure", "the colonoscopy is completed with clear visualization"],
  ["a diabetic client kept NPO before surgery", "a low morning blood glucose after insulin was given while fasting", "treat the hypoglycemia per protocol and clarify insulin orders for NPO status", "I will ask how to adjust my insulin whenever I cannot eat", "the client's glucose remains stable throughout the perioperative period"],
  ["a client after a thyroidectomy", "tingling around the mouth and twitching when the cheek is tapped", "check the calcium level and keep calcium gluconate readily available", "I will report numbness or tingling around my lips or fingers", "the client's calcium remains normal after surgery"],
];

export const EXTRA_GERONTOLOGY: ExtraItem[] = [
  ["an older adult taking multiple high-risk medications", "dizziness and two near-falls since starting a new sedative", "complete a medication reconciliation and review high-risk drugs with the provider", "I will bring all my medicine containers to every appointment", "the client's regimen is simplified with no further falls"],
  ["an older adult with sudden new urinary incontinence", "incontinence starting abruptly with confusion and foul-smelling urine", "assess for a urinary tract infection because new incontinence is often reversible", "I will keep drinking fluids regularly instead of restricting them", "the client regains continence once the cause is treated"],
  ["an older adult caring for a spouse with dementia", "caregiver exhaustion, weight loss, and social withdrawal", "assess caregiver strain and connect the family with respite services", "I will accept help and take regular breaks from caregiving", "the caregiver's wellbeing improves with support services"],
  ["an older adult with signs of possible elder abuse", "unexplained bruises in various stages of healing and a fearful manner", "interview the client alone and report suspected abuse according to the law", "I know I can speak privately with my nurse about my safety", "the client is protected with a safety plan in place"],
  ["a community experiencing a foodborne illness outbreak", "multiple residents ill after a community gathering", "report the outbreak to public health authorities and help identify the source", "I will refrigerate leftovers promptly and cook foods thoroughly", "no further cases occur once the source is controlled"],
  ["an older adult with age-related hearing loss", "withdrawal from conversations and apparent confusion when spoken to", "face the client, speak clearly in a lower tone, and reduce background noise", "I will wear my hearing aids and ask people to face me when speaking", "the client participates in conversations and activities again"],
  ["an older adult recently bereaved", "poor appetite, insomnia, and expressions of hopelessness months after the loss", "screen for depression and suicide risk because grief and depression can overlap", "I will join the grief support group in my community", "the client re-engages in daily activities with improved mood"],
  ["a homebound older adult after hospital discharge", "missed follow-up visits and confusion about the new medications", "arrange home-based follow-up and a clear, written medication schedule", "I will use my pill organiser and keep my follow-up appointments", "the client avoids readmission through successful home management"],
  ["an older adult with osteoporosis living alone", "severely reduced bone density with cluttered walkways at home", "conduct a home fall-hazard assessment and review bone-protective therapy", "I will remove loose rugs and install grab bars in the bathroom", "the client remains fracture-free in a safe home environment"],
  ["an older adult with early dementia who wanders at night", "night-time wandering with an unlocked exterior door", "recommend door alarms, consistent routines, and safe-return identification", "family will secure the doors and enrol the client in a safe-return programme", "the client remains safe at home without wandering incidents"],
];
