// Test-taking strategies shown in the Strategies library.
//
// Extracted from seed.ts so that the admin curriculum-update route can
// import them without pulling in the destructive full seed, which deletes
// and recreates users, questions and payment records.
//
// Examples are set in Ghanaian clinical settings and use British spelling,
// SI units and NMC scope-of-practice terminology.

export type StrategyDef = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  content: string[];
  example: string;
  icon: string;
  readTimeMinutes: number;
  videoId?: string;
  videoTitle?: string;
};

export const STRATEGY_DEFS: StrategyDef[] = [
  {
    slug: "abc-prioritization",
    title: "ABC Prioritisation Framework",
    category: "Prioritisation",
    summary: "Use Airway, Breathing and Circulation to decide who or what to attend to first.",
    content: [
      "When a question asks 'which client should the nurse see first' or 'which finding is priority,' check for airway problems first, then breathing, then circulation.",
      "A client who cannot speak, is choking, or has stridor outranks a client with a breathing problem alone.",
      "A client having sudden difficulty breathing outranks a client with a circulation problem such as bleeding or low blood pressure, unless the bleeding is massive and immediately life-threatening.",
      "Chronic or stable findings (like a well-managed condition) are almost never the priority when an acute ABC problem is present in another option.",
      "If two options both involve breathing, choose the one that is new, sudden, or worsening over one that is chronic or stable.",
    ],
    example: "Four patients on a district hospital ward: one with stable chronic asthma, one who has developed stridor after a blood transfusion, one with a healing surgical wound, and one anxious about discharge. Stridor threatens the airway — go to that patient first.",
    icon: "triangle",
    readTimeMinutes: 4,
    videoId: "xnlu4S4qjsU",
    videoTitle: "ABC Nursing (Airway Breathing Circulation) prioritisation guide",
  },
  {
    slug: "maslows-hierarchy",
    title: "Maslow's Hierarchy for Exam Questions",
    category: "Prioritisation",
    summary: "Physiological needs come before safety, and safety comes before psychosocial needs.",
    content: [
      "Rank needs in this order: physiological (oxygen, food, fluids, elimination) → safety → love/belonging → self-esteem → self-actualization.",
      "A physical symptom (pain, shortness of breath, bleeding) almost always outranks an emotional or social concern in a 'priority' question.",
      "Use this alongside ABCs: ABCs help you choose between two physiological problems; Maslow helps you choose between a physiological problem and a psychosocial one.",
      "Don't ignore psychosocial answers completely — if all options are physiologically equal or already addressed, the psychosocial option may be correct.",
    ],
    example: "A patient with new chest pain and a patient distressed about an HIV diagnosis both need you. The chest pain is physiological and potentially life-threatening, so it is attended to first — but return to the second patient, because the distress is real and also needs a nurse.",
    icon: "layers",
    readTimeMinutes: 3,
    videoId: "NiJOy1SObxM",
    videoTitle: "Maslow’s Hierarchy of Needs: Exam Prioritisation Made Simple",
  },
  {
    slug: "nursing-process-adpie",
    title: "The Nursing Process (ADPIE)",
    category: "Prioritisation",
    summary: "Assess before you diagnose, plan, implement, or evaluate — unless the client is unsafe.",
    content: [
      "ADPIE stands for Assessment, Diagnosis, Planning, Implementation, and Evaluation.",
      "When choices include both an assessment and an intervention, choose the assessment first — you need data before you act.",
      "Exception: if the client is in immediate danger (choking, cardiac arrest, haemorrhage), intervene immediately rather than continuing to assess.",
      "Evaluation questions ask whether a goal was met — match the evaluation finding directly back to the original goal of care.",
    ],
    example: "A patient on the medical ward reports new abdominal pain. Before giving the prescribed analgesia, assess the pain: site, onset, character, severity, and whether the abdomen is rigid. A rigid abdomen changes the answer from 'give analgesia' to 'call the medical officer now'.",
    icon: "compass",
    readTimeMinutes: 4,
    videoId: "am9zN5calho",
    videoTitle: "How to Use the Nursing Process (ADPIE) to Prioritize Care",
  },
  {
    slug: "five-rights-of-delegation",
    title: "The Five Rights of Delegation",
    category: "Delegation",
    summary: "Right task, right circumstance, right person, right direction, right supervision.",
    content: [
      "Right task: only delegate tasks that are within the delegatee's scope of practice and that are routine, stable, and predictable.",
      "Right circumstance: the client's condition must be stable enough for the task to be delegated safely.",
      "Right person: match the task to the level of training — a ward assistant can give basic care such as bathing, routine observations and walking a stable patient; an enrolled nurse works within a defined scope; assessment, teaching and evaluation stay with the registered nurse.",
      "Right direction/communication: give clear, specific instructions about what to do and what to report back.",
      "Right supervision: the registered nurse must follow up, evaluate the outcome, and remains accountable for the delegated task.",
      "Never delegate assessment, evaluation, teaching, or care of unstable clients to unlicensed ward assistants.",
    ],
    example: "You may delegate bathing a stable patient to a ward assistant, but you may not delegate assessing a new wound, teaching a newly diagnosed diabetic, or the first observation after a blood transfusion is started. You delegate the task; you keep the accountability.",
    icon: "list",
    readTimeMinutes: 5,
    videoId: "JszfqVZ0Ntw",
    videoTitle: "The Five Rights of Nursing Delegation explained",
  },
  {
    slug: "therapeutic-communication",
    title: "Recognising Therapeutic Communication",
    category: "Communication",
    summary: "Choose responses that are open-ended, empathetic, and client-centered.",
    content: [
      "Favor open-ended questions and reflective statements ('Tell me more about that,' 'It sounds like you're feeling...') over closed yes/no questions.",
      "Avoid answer choices that give advice, judge, offer false reassurance ('everything will be fine'), change the subject, or ask 'why' (which sounds accusatory).",
      "The best answer usually acknowledges the client's feelings before problem-solving.",
      "Silence and active listening are valid therapeutic techniques — don't assume the nurse must always be talking.",
      "When in doubt, choose the response that keeps the focus on the client's feelings and experience.",
    ],
    example: "A woman waiting for theatre says, 'I am afraid I will not wake up.' The therapeutic reply is 'Tell me what worries you most about the operation,' not 'Do not worry, the surgeon here is very good.' Reassurance closes the conversation; an open question opens it.",
    icon: "message",
    readTimeMinutes: 4,
    videoId: "svMEO66BlJY",
    videoTitle: "Therapeutic Communication Techniques in Nursing",
  },
  {
    slug: "sbar-handoff",
    title: "Using SBAR for Clear Communication",
    category: "Communication",
    summary: "Situation, Background, Assessment, Recommendation — a structure for handoffs and medical officer calls.",
    content: [
      "Situation: state who you are and briefly describe the current problem.",
      "Background: give relevant history — diagnosis, recent treatments, and baseline status.",
      "Assessment: share your clinical impression, including current vital signs and key findings.",
      "Recommendation: state what you want the listener to do or ask for guidance.",
      "On exam questions about communication or handoff, the best answer usually includes all four SBAR elements rather than an incomplete or disorganized report.",
    ],
    example: "'This is the nurse on the female medical ward calling about Madam Mensah in bed 4 (S). She had a laparotomy yesterday (B). Her blood pressure has fallen to 88/54 and her pulse is 124 (A). Please can you review her now, and may I start a fluid bolus (R)?'",
    icon: "message",
    readTimeMinutes: 4,
    videoId: "uERVFUMo2Vo",
    videoTitle: "I-SBAR Shift Report Handoff: Nurse-to-Nurse Demonstration",
  },
  {
    slug: "least-restrictive-safety",
    title: "Choosing the Least Restrictive, Safest Option",
    category: "Safety",
    summary: "When several safety interventions are offered, pick the least restrictive one that still keeps the client safe.",
    content: [
      "Restraints and seclusion are always a last resort — try reorientation, environmental changes, and verbal de-escalation first.",
      "For fall risk, choose interventions like a low bed and frequent rounding before restraints.",
      "For a confused client pulling at tubes, try distraction, camouflage, or a sitter before restraints.",
      "If an option is clearly unsafe or violates a client's rights, eliminate it immediately, even if it seems easier for staff.",
    ],
    example: "A confused elderly man keeps trying to climb out of bed. The correct first answer is to move him nearer the nurses' station, lower the bed and involve a relative to sit with him — not to apply a restraint. Under the Mental Health Act 846, restriction requires imminent danger, not inconvenience.",
    icon: "shield",
    readTimeMinutes: 3,
  },
  {
    slug: "eliminate-absolutes-in-teaching",
    title: "Spotting Wrong Answers in Teaching Questions",
    category: "Test-Taking Mindset",
    summary: "Absolute words and unsafe shortcuts are almost always wrong in 'client understands teaching' questions.",
    content: [
      "Be suspicious of options with 'never,' 'always,' 'only,' or 'as long as I feel fine' — real self-care usually has some nuance.",
      "'Needs further teaching' questions ask you to find the INCORRECT statement — read the stem twice to be sure which direction you're looking for.",
      "Correct statements usually match a specific safety teaching point taught for that condition (dosing schedule, warning signs, follow-up).",
      "If a statement describes stopping a medication abruptly without medical officer guidance, it's almost always incorrect understanding.",
    ],
    example: "'You must never eat local rice again' is almost certainly wrong. 'You can eat rice, but let us look at the portion size and what you add to it' is almost certainly right. Absolute words such as always, never and all usually mark the distractor.",
    icon: "eye",
    readTimeMinutes: 3,
  },
  {
    slug: "assess-before-you-act",
    title: "Assess Before You Act — Unless It Is an Emergency",
    category: "Prioritisation",
    summary: "When choices mix assessment and intervention, gather data first — unless the client is unstable.",
    content: [
      "If one answer choice is 'assess' and another is 'treat,' assess first when the client is stable enough to allow it.",
      "In a true emergency (cardiac arrest, choking, active haemorrhage), skip straight to the life-saving intervention.",
      "Look for clues in the stem such as 'stable,' 'alert,' or normal-sounding vital signs — these suggest time to assess first.",
      "Look for clues such as 'unresponsive,' 'not breathing,' or critical vital signs — these suggest you must act immediately.",
    ],
    example: "A patient's infusion site is swollen and painful. Assess first? No — this is the exception. Stop the infusion and remove the cannula, then assess. When a device is causing the harm, remove the device first.",
    icon: "compass",
    readTimeMinutes: 3,
  },
  {
    slug: "select-all-that-apply-strategy",
    title: "Strategy for Select-All-That-Apply Questions",
    category: "Test-Taking Mindset",
    summary: "Evaluate each option independently as true or false rather than comparing options to each other.",
    content: [
      "Treat every option as its own true/false statement about the scenario — don't assume there's only one correct answer.",
      "There is no partial credit strategy trick — focus on accuracy for each option rather than guessing a 'typical number' of correct answers.",
      "Eliminate options that are absolute, outside the nurse's role, or contradict the scenario.",
      "If you're unsure about an option, ask: 'Is this statement safe, accurate, and directly supported by the scenario?' If yes, select it.",
    ],
    example: "Treat each option as a separate true-or-false question about the same patient. For 'select all that apply to severe malaria', ask of each option individually: is this true of severe malaria, yes or no? Do not look for a set number of correct answers — there is no fixed count.",
    icon: "list",
    readTimeMinutes: 3,
    videoId: "WfvSEYS0Ntg",
    videoTitle: "Nursing Exam: Select All That Apply (SATA) Questions Strategy",
  },
  {
    slug: "lab-value-quick-reference",
    title: "Quick Reference: Key Values in SI Units",
    category: "Pharmacology",
    summary: "Knowing a handful of critical lab values makes 'priority finding' questions much easier.",
    content: [
      "Sodium: 135-145 mEq/L. Potassium: 3.5-5.0 mEq/L. Calcium: 9-10.5 mg/dL. Magnesium: 1.5-2.5 mEq/L.",
      "Haemoglobin: about 12-16 g/dL (varies by sex). Platelets: 150,000-400,000/mm3. WBC: 5,000-10,000/mm3.",
      "Therapeutic INR on warfarin: usually 2-3. Therapeutic digoxin level: 0.5-2.0 ng/mL. Therapeutic lithium level: 0.6-1.2 mEq/L.",
      "Know which values are critically high or low enough to require immediate action versus values that only need monitoring.",
      "When a question gives you a lab value, decide first whether it's normal, mildly abnormal, or critically abnormal before choosing an answer.",
    ],
    example: "Ghanaian laboratories report in SI units, so learn them in that form: potassium 3.5–5.0 mmol/L, sodium 135–145 mmol/L, random glucose under 11.1 mmol/L, creatinine 60–120 µmol/L, haemoglobin 12–16 g/dL in women. A value means little without knowing when the sample was taken.",
    icon: "flask",
    readTimeMinutes: 5,
  },
  {
    slug: "dosage-calculation-strategy",
    title: "A Reliable Approach to Dosage Calculations",
    category: "Pharmacology",
    summary: "Use dimensional analysis and always sanity-check your final answer.",
    content: [
      "Write out the desired dose, the dose on hand, and the quantity, then cancel units step by step (dimensional analysis) rather than memorizing formulas.",
      "Convert all units to the same system before calculating (e.g., convert pounds to kilograms).",
      "After calculating, ask: does this dose make clinical sense? A dose of 40 tablets or 500 mL/hr for a routine medication is a red flag to recheck your math.",
      "For IV drip rates, remember: rate (mL/hr) x drop factor (gtt/mL) ÷ 60 minutes = drops per minute.",
      "Practice with real-world numbers regularly — dosage calculation is a skill that fades quickly without practice.",
    ],
    example: "A child weighing 14 kg needs maintenance fluid. Use 4-2-1: 4 mL/kg for the first 10 kg is 40, plus 2 mL/kg for the next 4 kg is 8, giving 48 mL/hour. Always finish with a sense-check: is 48 mL/hour reasonable for a small child? Yes. A figure of 480 would not be.",
    icon: "flask",
    readTimeMinutes: 5,
    videoId: "Uc-Etqbb24Y",
    videoTitle: "Nursing Dosage Calculations Using 3 Methods: Desired Over Have, Ratio/Proportion, & Dimensional",
  },
  {
    slug: "infection-control-decision-tree",
    title: "Choosing the Right Precautions",
    category: "Safety",
    summary: "Match the mode of transmission to the correct precaution category.",
    content: [
      "Airborne precautions (N95 + negative pressure room): tuberculosis, measles, varicella (chickenpox).",
      "Droplet precautions (mask within 3-6 feet): influenza, pertussis, mumps, meningitis (bacterial), rubella.",
      "Contact precautions (gown and gloves): MRSA, VRE, C. difficile (use soap and water, not just alcohol sanitizer), scabies.",
      "Standard precautions apply to every client, every time, regardless of diagnosis.",
      "If a question describes the mode of spread (airborne droplet nuclei vs. large droplets vs. direct contact), match it to the correct category rather than memorizing every disease individually.",
    ],
    example: "Ask how the organism travels. Tuberculosis is airborne, so it needs a well-ventilated single room and a respirator. Cholera is faecal-oral, so it needs gloves, an apron and handwashing with soap and running water rather than alcohol rub. Match the barrier to the route.",
    icon: "shield",
    readTimeMinutes: 4,
    videoId: "esE1T39KgqY",
    videoTitle: "Isolation Precautions Mnemonics: Contact, Droplet, and Airborne",
  },
  {
    slug: "time-management-matrix",
    title: "Prioritising a Busy Shift",
    category: "Prioritisation",
    summary: "Sort your task list into urgent/important categories to decide what to do first, next, and last.",
    content: [
      "Urgent and important: life-threatening or rapidly changing situations — do these first.",
      "Important but not urgent: scheduled medications, assessments, and treatments — plan these next.",
      "Urgent but less important clinically: call lights, non-urgent requests — delegate these when possible.",
      "Neither urgent nor important: tasks that can wait until later in the shift or be delegated entirely.",
      "Reassess your priorities throughout the shift — a stable client can become unstable and jump to the top of the list.",
    ],
    example: "At handover you have: a patient due for artesunate now, a patient asking for the bedpan, a discharge letter to write, and a relative wanting to talk. The artesunate is time-critical and life-saving; the bedpan is dignity and cannot wait long; the letter can wait; the relative needs a specific time, not a brush-off.",
    icon: "clock",
    readTimeMinutes: 4,
  },
  {
    slug: "client-centered-vs-task-centered",
    title: "Choose the Patient-Centred Answer",
    category: "Test-Taking Mindset",
    summary: "When in doubt, pick the option that focuses on the client's individual needs over routine or convenience.",
    content: [
      "Exam questions favor answers that individualize care over answers that describe a rigid routine or facility convenience.",
      "Eliminate options that prioritize staff convenience, efficiency, or 'the way it's always done' over client safety or preference.",
      "Look for answers that involve the client in decision-making when appropriate.",
      "If two answers seem clinically similar, pick the one that better respects the client's autonomy and individual situation.",
    ],
    example: "A woman refuses to be examined by a male student. The patient-centred answer is to arrange a female examiner or a chaperone, not to explain that the ward is short-staffed. Ward convenience is almost never the correct answer in an examination.",
    icon: "target",
    readTimeMinutes: 3,
  },
  {
    slug: "normal-vital-sign-ranges",
    title: "Quick Reference: Normal Ranges Across the Lifespan",
    category: "Pharmacology",
    summary: "Recognize abnormal vital signs quickly so you can spot the priority finding faster.",
    content: [
      "Temperature: 97.8-99.1°F (36.5-37.3°C) oral average.",
      "Heart rate: 60-100 beats/min. Below 60 is bradycardia; above 100 is tachycardia.",
      "Respiratory rate: 12-20 breaths/min. Below 12 or above 24 needs prompt attention.",
      "Blood pressure: around 90/60 to 120/80 mmHg for most healthy adults; values must be interpreted in context of the client's baseline.",
      "Oxygen saturation: 95-100% is generally normal; below 90% is a priority finding requiring action.",
    ],
    example: "Newborn: temperature 36.5–37.5 °C, respiratory rate 30–60, heart rate 120–160. Adult: 36.1–37.2 °C, respiratory rate 12–20, pulse 60–100. In IMCI, fast breathing is 60 or more under 2 months, 50 or more from 2–11 months, and 40 or more from 1–5 years.",
    icon: "activity",
    readTimeMinutes: 3,
  },
  {
    slug: "emergency-urgent-nonurgent",
    title: "Sorting Emergency, Urgent and Non-Urgent",
    category: "Prioritisation",
    summary: "Use this three-tier system for triage- and prioritisation-style questions.",
    content: [
      "Emergent: immediate threat to life or limb (chest pain, severe bleeding, unresponsiveness) — see or treat right away.",
      "Urgent: needs attention soon but can wait a short time safely (moderate pain, non-life-threatening injury).",
      "Non-urgent: stable clients with minor complaints — see last among competing demands.",
      "When ranking multiple clients, sort them mentally into these three tiers before deciding the exact order.",
    ],
    example: "A child with a convulsion is an emergency. A man with a diabetic foot ulcer and a fever is urgent. A woman collecting her routine antihypertensive is non-urgent. In an emergency, the question is what will kill this patient in the next few minutes.",
    icon: "flag",
    readTimeMinutes: 3,
  },
  {
    slug: "test-anxiety-management",
    title: "Managing Test Anxiety on Exam Day",
    category: "Test-Taking Mindset",
    summary: "A calm, steady approach improves recall and reasoning during high-stakes exams.",
    content: [
      "Use slow, deep breathing if you feel your heart racing during the exam — this activates your body's relaxation response.",
      "If you get stuck on a hard question, flag it (if allowed) and keep moving rather than losing time you need for other questions.",
      "Positive self-talk ('I have prepared for this') reduces the stress response that can block memory recall.",
      "The night before the exam, prioritize sleep over last-minute cramming — a rested brain reasons through questions far better.",
      "Remember that one hard question does not determine the outcome — stay focused on the next question in front of you.",
    ],
    example: "On the day of the computer-based paper, arrive early, breathe out slowly for longer than you breathe in, and remember that you can flag a question and return to it. Spending five minutes on one item costs you three easier marks elsewhere.",
    icon: "compass",
    readTimeMinutes: 4,
  },
  {
    slug: "process-of-elimination",
    title: "Mastering the Process of Elimination",
    category: "Test-Taking Mindset",
    summary: "Cross out clearly wrong answers first to improve your odds even when you're unsure.",
    content: [
      "Read all four options before choosing — the 'best' answer is a comparative decision, not just a search for a true statement.",
      "Eliminate any option that is unsafe, illegal, or outside the nurse's scope of practice immediately.",
      "Eliminate options that are true in general but do not directly answer the specific question being asked.",
      "Between two reasonable-looking options, look for the one that is more specific and directly tied to the scenario.",
      "If you must guess, guess among your remaining narrowed-down options rather than all four.",
    ],
    example: "If two options say essentially the same thing in different words, neither is usually correct, because a single-best-answer question cannot have two identical answers. Strike them both and choose between what remains.",
    icon: "eye",
    readTimeMinutes: 3,
  },
  {
    slug: "read-the-stem-carefully",
    title: "Read the Question Stem Carefully",
    category: "Test-Taking Mindset",
    summary: "Misreading a keyword like 'first,' 'best,' or 'except' is one of the most common causes of missed questions.",
    content: [
      "Underline (mentally or physically) key words such as 'first,' 'priority,' 'best,' 'most appropriate,' or 'further teaching is needed.'",
      "Watch for negative phrasing such as 'which action should the nurse avoid' — these flip the logic of the question.",
      "Make sure you know whether the question wants the correct understanding or the incorrect understanding (needs more teaching).",
      "Reread the stem after choosing an answer to confirm you answered the question that was actually asked.",
    ],
    example: "'Which action should the nurse take first' and 'which action is contraindicated' are opposite questions. Underline first, best, initial, most, except and contraindicated before you read the options — that one word decides the answer.",
    icon: "eye",
    readTimeMinutes: 3,
  },
  {
    slug: "what-not-to-delegate",
    title: "What a Nurse Must Never Delegate",
    category: "Delegation",
    summary: "Assessment, teaching, evaluation, and unstable clients always stay with the registered nurse.",
    content: [
      "The RN cannot delegate the nursing assessment, the plan of care, client teaching, or evaluation of care to unlicensed ward assistants.",
      "Unstable or complex clients should not be assigned tasks delegated to ward assistants, even routine ones, until they are stabilised.",
      "Intravenous medication administration is outside a ward assistant's scope entirely, and an enrolled nurse's scope is narrower than a registered nurse's — check the specific task against the scope set by the Nursing and Midwifery Council.",
      "When answering delegation questions, ask: 'Is this a stable, routine, predictable task that doesn't require nursing judgment?' If not, keep it with the registered nurse.",
    ],
    example: "You may not delegate assessment, the first observation of an unstable patient, health teaching, evaluating whether a treatment worked, or any decision requiring nursing judgement. A ward assistant may take a routine temperature; only you may interpret what it means.",
    icon: "list",
    readTimeMinutes: 4,
  },
  {
    slug: "cultural-sensitivity-in-answers",
    title: "Selecting Culturally Appropriate Answers",
    category: "Communication",
    summary: "The best exam answer respects a client's cultural and religious preferences whenever it is safe to do so.",
    content: [
      "Avoid answers that impose the nurse's own beliefs or assume all clients want the same type of care.",
      "Whenever an option offers to incorporate the client's cultural, spiritual, or personal preference safely, it is usually the better choice.",
      "Ask the client about their preferences rather than assuming based on their background.",
      "Cultural accommodation should never compromise essential safety — balance respect for preferences with clinical necessity.",
    ],
    example: "A family wishes to bring herbal preparations to a patient on antiretroviral therapy. The correct answer explores what they are using and checks for interactions, rather than forbidding it outright. Dismissing a belief ends the conversation and the patient simply stops telling you.",
    icon: "message",
    readTimeMinutes: 3,
  },
  {
    slug: "recognizing-normal-vs-abnormal-newborn",
    title: "Newborn Assessment: Normal or Needs Action",
    category: "Prioritisation",
    summary: "Know the expected newborn transition findings so abnormal ones stand out immediately.",
    content: [
      "Expected: acrocyanosis (blue hands/feet) in the first 24 hours, mild jaundice after 24 hours, a heart rate of 110-160, and periodic breathing.",
      "Needs follow-up: central cyanosis at any time, grunting/retractions, jaundice in the first 24 hours, or a temperature below 97.7°F.",
      "Compare each finding to expected newborn transition physiology before deciding if it's a priority.",
      "When several newborn findings are listed, the one that is outside expected transition parameters is usually the priority answer.",
    ],
    example: "Milia, Mongolian blue spots and physiological jaundice appearing after 24 hours are normal. Jaundice within the first 24 hours is always pathological and needs immediate investigation. The timing, not the yellow colour, is what makes it an emergency.",
    icon: "triangle",
    readTimeMinutes: 4,
  },
  {
    slug: "answering-pharmacology-teaching-questions",
    title: "Pharmacology Teaching Question Strategy",
    category: "Pharmacology",
    summary: "Tie every medication back to its most important safety teaching point.",
    content: [
      "For every high-alert medication, know one key monitoring parameter (e.g., apical pulse for digoxin, INR for warfarin, respiratory rate for opioids).",
      "Correct teaching statements usually describe how the client will self-monitor for that specific parameter or warning sign.",
      "Be alert to teaching statements that describe stopping a medication abruptly, doubling a missed dose, or ignoring a warning sign — these usually indicate a need for further teaching.",
      "When unsure, connect the drug to its class first (e.g., beta-blocker, anticoagulant, opioid) — many teaching points apply to the whole class.",
    ],
    example: "Rifampicin turns urine and tears orange — harmless, but the patient must be warned or they will stop the drug. Ask what the patient needs to know to keep taking the medicine safely, not what the pharmacology textbook says about its mechanism.",
    icon: "pill",
    readTimeMinutes: 4,
  },
  {
    slug: "nmc-computer-based-format",
    title: "Sitting the NMC Computer-Based Paper",
    category: "Exam Technique",
    summary: "The licensing examination is entirely multiple choice and delivered on a computer. Practise the format, not just the content.",
    content: [
      "The paper is computer-based and made up entirely of multiple-choice questions. The old written essay papers have been discontinued, so practise selecting single best answers under time pressure rather than planning essays.",
      "You can usually flag an item and come back to it. Use that instead of stalling: an unanswered easy question later in the paper costs the same mark as the hard one you are stuck on.",
      "There is no negative marking for a wrong answer in a single-best-answer paper, so never leave a question blank. Eliminate what you can and choose from what remains.",
      "Work out your pace before the day. Divide the total questions by the total minutes, and check yourself against that pace at the quarter and half marks.",
      "Read the last line of the stem first if the scenario is long. Knowing whether it asks for the first action or the contraindicated action tells you what to look for as you read.",
    ],
    example: "If you have 100 questions in 120 minutes, that is a little over one minute each. At the 30-minute mark you should be near question 25. If you are at question 12, you are reading too slowly and need to commit to answers faster.",
    icon: "monitor",
    readTimeMinutes: 4,
  },
  {
    slug: "ghana-guideline-first",
    title: "Answer from the Ghana Standard Treatment Guidelines",
    category: "Exam Technique",
    summary: "Where a Ghanaian protocol exists, it outranks a textbook written for another country.",
    content: [
      "When an option matches the Ghana Standard Treatment Guidelines or a Ghana Health Service protocol, that is almost always the intended answer, even if an international textbook offers an alternative.",
      "Know the national schedules by heart: the EPI immunisation schedule, IPTp-SP from 16 weeks, artesunate dosing by weight, the IMCI classifications, and the partograph alert and action lines.",
      "Drug availability matters. An answer built on a medicine or investigation that is not routinely available at a district hospital is unlikely to be the expected one.",
      "Referral pathways follow the GHS structure: CHPS compound, health centre, district hospital, regional hospital, teaching hospital. Questions about escalation usually test that sequence.",
      "Notifiable diseases are reported on suspicion under IDSR, not after laboratory confirmation. Waiting for a result is a recurring wrong answer.",
    ],
    example: "A question asks about malaria prophylaxis in pregnancy. The expected answer is IPTp-SP from 16 weeks, given monthly, to at least three doses under direct observation — the national protocol — not a regimen from a textbook written for travellers.",
    icon: "flag",
    readTimeMinutes: 4,
  },
  {
    slug: "last-line-first",
    title: "Read the Last Line First",
    category: "Exam Technique",
    summary: "In a long clinical scenario, the question being asked determines which details matter.",
    content: [
      "Long stems are written to bury one decisive detail among several irrelevant ones. Reading the final question first tells you what you are hunting for.",
      "If the question asks for the priority action, look for the sign that is most immediately life-threatening, not the most abnormal number.",
      "If it asks what to report, look for the finding that changes management. A fever of 38 °C is abnormal in most patients, but in a child with sickle cell disease it is an emergency.",
      "If it asks what to do first among several correct actions, all the options may be things you would genuinely do. Sequence is what is being tested.",
      "Watch for a negative stem: except, contraindicated, least appropriate, requires further teaching. Here the three good answers are the distractors.",
    ],
    example: "A stem describes a 24-year-old with fever, a positive malaria test, a respiratory rate of 32 and reduced consciousness, then asks which finding is most urgent to report. Reading that first, you scan for the danger sign rather than the diagnosis: reduced consciousness defines severe malaria.",
    icon: "search",
    readTimeMinutes: 3,
  },
];
